INSERT INTO [Oyuncaklar] ([UrunAdi], [Aciklama], [Fiyat], [KapakResimUrl], [YeniCikanMi], [CokSatanMi], [StokAdedi], [YasGrubu], [Marka], [KategoriId])
VALUES
('LEGO City Polis İstasyonu', '785 parça, 3 katlı polis merkezi.', 1450.00, '/img/oyuncak/urun_1.jpg', 1, 1, 15, '6+', 'LEGO', NULL),
('Barbie Sonsuz Hareket Bebeği', '22 eklemi ile gerçekçi hareket kabiliyeti.', 550.00, '/img/oyuncak/urun_2.jpg', 0, 1, 30, '3+', 'Mattel', NULL),
('Hot Wheels 50''li Araba Seti', 'Dev koleksiyon başlangıç seti.', 2200.00, '/img/oyuncak/urun_3.jpg', 0, 1, 10, '3+', 'Hot Wheels', NULL),
('Monopoly Dijital Bankacılık', 'Nakit para olmadan hızlı emlak ticareti.', 850.00, '/img/oyuncak/urun_4.jpg', 1, 0, 20, '8+', 'Hasbro', NULL),
('Nerf Ultra One', '25 dart kapasiteli tam otomatik dart tabancası.', 1200.00, '/img/oyuncak/urun_5.jpg', 1, 1, 12, '8+', 'Nerf', NULL),
('Fisher-Price Eğitici Tablet', 'Sesli ve ışıklı alfabe öğrenme tableti.', 450.00, '/img/oyuncak/urun_6.jpg', 0, 1, 40, '12-36 Ay', 'Fisher-Price', NULL),
('Play-Doh Mutfak Atölyesi', 'Çeşitli kalıplarla hamurdan yemek yapma seti.', 380.00, '/img/oyuncak/urun_7.jpg', 0, 0, 50, '3+', 'Hasbro', NULL),
('Scrabble Junior', 'Çocuklar için resimli kelime oyunu.', 420.00, '/img/oyuncak/urun_8.jpg', 0, 1, 25, '5+', 'Mattel', NULL),
('Remote Control Rock Crawler', 'Her araziye uygun 4x4 kumandalı araç.', 1100.00, '/img/oyuncak/urun_9.jpg', 1, 0, 18, '6+', 'Maisto', NULL),
('Clementoni Robotik Laboratuvarı', 'Kendi robotunu yap ve programla.', 950.00, '/img/oyuncak/urun_10.jpg', 1, 1, 15, '8+', 'Clementoni', NULL),
('Star Wars Millennium Falcon LEGO', '1351 parça dev koleksiyon figürü.', 3500.00, '/img/oyuncak/urun_11.jpg', 0, 1, 5, '12+', 'LEGO', NULL),
('LOL Surprise! O.M.G. Bebek', 'Moda ikonu büyük LOL bebeği.', 750.00, '/img/oyuncak/urun_12.jpg', 1, 1, 22, '4+', 'MGA', NULL),
('Transformers Optimus Prime', 'Tıra dönüşebilen metalik figür.', 650.00, '/img/oyuncak/urun_13.jpg', 0, 0, 30, '6+', 'Hasbro', NULL),
('Manyetik Satranç Takımı', 'Seyahat boyu mıknatıslı satranç.', 250.00, '/img/oyuncak/urun_14.jpg', 0, 1, 100, '6+', 'StarGames', NULL),
('Peluş Ayı Nova 100cm', 'Dev boy yumuşacık uyku arkadaşı.', 900.00, '/img/oyuncak/urun_15.jpg', 1, 1, 10, '0+', 'NovaToys', NULL),
('Uno Kart Oyunu', 'Eğlenceli klasik aile kart oyunu.', 120.00, '/img/oyuncak/urun_16.jpg', 0, 1, 200, '7+', 'Mattel', NULL),
('Puzzle 1000 Parça: Galaksi', 'Uzay temalı zorlayıcı yetişkin puzzle.', 280.00, '/img/oyuncak/urun_17.jpg', 1, 0, 45, '12+', 'Anatolian', NULL),
('Ahşap Mutfak Seti', 'Doğal malzemeden üretilmiş oyuncak mutfak.', 1850.00, '/img/oyuncak/urun_18.jpg', 0, 1, 8, '3+', 'Woody', NULL),
('Marvel Spider-Man Figür', '30 cm boyunda eklemli aksiyon figürü.', 450.00, '/img/oyuncak/urun_19.jpg', 1, 1, 40, '4+', 'Hasbro', NULL),
('Baby Alive Mama Yiyen Bebek', 'Gerçek yemek yiyen ve altını kirleten bebek.', 850.00, '/img/oyuncak/urun_20.jpg', 0, 1, 25, '3+', 'Hasbro', NULL),
('Hatchimals Pixies', 'Yumurtadan çıkan uçan peri bebek.', 620.00, '/img/oyuncak/urun_21.jpg', 1, 0, 35, '5+', 'Spin Master', NULL),
('Thomas & Friends Tren Seti', 'Raylı ve pilli Thomas tren seti.', 580.00, '/img/oyuncak/urun_22.jpg', 0, 1, 20, '3+', 'Fisher-Price', NULL),
('Enchantimals Bebek ve Hayvanı', 'Doğa dostu temalı mini bebekler.', 220.00, '/img/oyuncak/urun_23.jpg', 0, 1, 60, '4+', 'Mattel', NULL),
('Jenga Klasik', 'Denge ve strateji oyunu.', 350.00, '/img/oyuncak/urun_24.jpg', 0, 1, 150, '6+', 'Hasbro', NULL),
('Slime Dev Yapım Seti', 'Farklı renk ve kokularda slime kiti.', 180.00, '/img/oyuncak/urun_25.jpg', 1, 0, 80, '5+', 'NovaFun', NULL),
('Güneş Sistemi Maket Kiti', 'Karanlıkta parlayan gezegenler kiti.', 320.00, '/img/oyuncak/urun_26.jpg', 0, 1, 30, '8+', 'SciencePlay', NULL),
('Pilli Işıklı Keman', 'Müzik kulağını geliştiren başlangıç kemanı.', 450.00, '/img/oyuncak/urun_27.jpg', 1, 0, 15, '5+', 'MusicStar', NULL),
('Tabu XL', 'Yasaklı kelimeleri anlatma oyunu.', 550.00, '/img/oyuncak/urun_28.jpg', 0, 1, 40, '12+', 'Hasbro', NULL),
('Risk Strateji Oyunu', 'Dünya hakimiyeti için taktiksel savaş.', 720.00, '/img/oyuncak/urun_29.jpg', 0, 1, 20, '10+', 'Hasbro', NULL),
('Duyusal Kum Seti 2kg', 'Kurumayan, şekil alan kinetik kum.', 250.00, '/img/oyuncak/urun_30.jpg', 1, 1, 70, '3+', 'SandMagic', NULL),
('Frozen 2 Elsa Kostümü', 'Pelerinli ve taçlı özel kostüm.', 480.00, '/img/oyuncak/urun_31.jpg', 0, 1, 15, '4-6 Yaş', 'Disney', NULL),
('Eğitici Sayılar Abaküsü', 'Renkli boncuklu ahşap abaküs.', 150.00, '/img/oyuncak/urun_32.jpg', 0, 0, 50, '3+', 'Woody', NULL),
('Walkie Talkie Telsiz Seti', '3km menzilli şarjlı telsizler.', 650.00, '/img/oyuncak/urun_33.jpg', 1, 0, 25, '8+', 'SpyKit', NULL),
('Lego Technic Yarış Arabası', 'Mekanik aksamlı detaylı yapım seti.', 1150.00, '/img/oyuncak/urun_34.jpg', 1, 1, 12, '10+', 'LEGO', NULL),
('Büyük Boy Yazı Tahtası', 'Ayaklı, manyetik ve tebeşirli tahta.', 580.00, '/img/oyuncak/urun_35.jpg', 0, 1, 10, '3+', 'NovaArt', NULL),
('Minecraft Steve Figür Seti', 'Bloklar ve aksesuarlar içeren set.', 340.00, '/img/oyuncak/urun_36.jpg', 1, 0, 45, '6+', 'Mattel', NULL),
('Trivial Pursuit Aile Boyu', 'Genel kültür bilgi yarışması oyunu.', 620.00, '/img/oyuncak/urun_37.jpg', 0, 1, 18, '8+', 'Hasbro', NULL),
('Pilsan Akülü Araba 12V', 'Uzaktan kumandalı emniyet kemerli araç.', 7500.00, '/img/oyuncak/urun_38.jpg', 1, 1, 5, '3-8 Yaş', 'Pilsan', NULL),
('Twister Eğlence Matı', 'Vücut dengesini zorlayan grup oyunu.', 420.00, '/img/oyuncak/urun_39.jpg', 0, 1, 60, '6+', 'Hasbro', NULL),
('Doktor Seti Çantalı', 'Tüm tıbbi malzemeleri içeren set.', 220.00, '/img/oyuncak/urun_40.jpg', 0, 1, 90, '3+', 'ToyMed', NULL),
('Lego Duplo Hayvan Çiftliği', 'Okul öncesi çocuklar için büyük parçalar.', 680.00, '/img/oyuncak/urun_41.jpg', 1, 1, 20, '2+', 'LEGO', NULL),
('Batman Batmobile Araç', 'Zırhlı ve ışıklı Batman aracı.', 780.00, '/img/oyuncak/urun_42.jpg', 1, 0, 15, '4+', 'DC Comics', NULL),
('Barbie Veteriner Seti', 'Evcil hayvanlar ve muayene masası.', 650.00, '/img/oyuncak/urun_43.jpg', 0, 1, 25, '3+', 'Mattel', NULL),
('Süper Doktor Oyunu', 'Hastayı sarsmadan ameliyat etme oyunu.', 490.00, '/img/oyuncak/urun_44.jpg', 0, 1, 35, '6+', 'Hasbro', NULL),
('K' + 'Nex Mühendislik Seti', 'Çarklı ve hareketli modeller yapım kiti.', 890.00, '/img/oyuncak/urun_45.jpg', 1, 1, 14, '9+', 'K-Nex', NULL),
('Kız Kulesi Maketi', 'Lazer kesim ahşap 3D puzzle.', 180.00, '/img/oyuncak/urun_46.jpg', 0, 0, 100, '10+', 'Woody', NULL),
('Vahşi Hayvanlar Figür Seti', '12 adet gerçekçi orman hayvanı.', 320.00, '/img/oyuncak/urun_47.jpg', 0, 1, 50, '3+', 'WildLife', NULL),
('Teleskop Başlangıç Seti', 'Ay ve yıldızları gözlemlemek için.', 1450.00, '/img/oyuncak/urun_48.jpg', 1, 1, 8, '8+', 'SciencePlay', NULL),
('Bratz Retro Bebek', 'Koleksiyonluk özel seri Bratz.', 820.00, '/img/oyuncak/urun_49.jpg', 1, 0, 20, '6+', 'MGA', NULL),
('Domino 100 Parça Renkli', 'Devirme reaksiyonlu ahşap dominolar.', 240.00, '/img/oyuncak/urun_50.jpg', 0, 1, 80, '4+', 'Woody', NULL),
('Lego Ninjago Ejderha Seti', '640 parça, hareketli büyük ejderha.', 950.00, '/img/oyuncak/urun_51.jpg', 1, 1, 15, '8+', 'LEGO', NULL),
('Disney Princess Şato', 'Tüm prenses bebekler için dev şato.', 3800.00, '/img/oyuncak/urun_52.jpg', 1, 1, 4, '3+', 'Disney', NULL),
('Hot Wheels Şehir Macerası', 'Yılanlı ve devasa garaj seti.', 1650.00, '/img/oyuncak/urun_53.jpg', 0, 1, 10, '4+', 'Hot Wheels', NULL),
('Catan Masa Oyunu', 'Kaynak toplama ve yerleşim kurma oyunu.', 850.00, '/img/oyuncak/urun_54.jpg', 0, 1, 30, '10+', 'Kosmos', NULL),
('Bakugan Başlangıç Paketi', 'Mıknatıslı dönüşen savaşçı toplar.', 450.00, '/img/oyuncak/urun_55.jpg', 1, 0, 55, '6+', 'Spin Master', NULL),
('Paw Patrol Dev Devriye Aracı', 'Tüm köpekleri taşıyan büyük araç.', 1250.00, '/img/oyuncak/urun_56.jpg', 1, 1, 18, '3+', 'Spin Master', NULL),
('Pilsan Lego Masa Seti', 'Üzerinde lego yapılabilen çocuk masası.', 750.00, '/img/oyuncak/urun_57.jpg', 0, 1, 20, '2+', 'Pilsan', NULL),
('Harry Potter Asa (Işıklı)', 'Müzikli ve sesli büyücü asası.', 520.00, '/img/oyuncak/urun_58.jpg', 1, 1, 40, '6+', 'WizardWorld', NULL),
('Squishmallows Yumuşak Yastık', 'Özel dokulu büyük boy peluş.', 450.00, '/img/oyuncak/urun_59.jpg', 1, 1, 35, '0+', 'Kellytoy', NULL),
('Guess Who? (Bil Bakalım Kim?)', 'Karakter tahmin etme klasik oyunu.', 320.00, '/img/oyuncak/urun_60.jpg', 0, 1, 60, '6+', 'Hasbro', NULL),
('Lego Friends Kafe Seti', 'Minik figürlü şirin mahalle kafesi.', 580.00, '/img/oyuncak/urun_61.jpg', 0, 1, 25, '6+', 'LEGO', NULL),
('Magic Mixies Sihirli Kazan', 'Gerçek sisler içinden çıkan bebek.', 1850.00, '/img/oyuncak/urun_62.jpg', 1, 1, 12, '5+', 'Moose Toys', NULL),
('Hot Wheels Renk Değiştirenler', 'Suya girince renk değiştiren arabalar.', 180.00, '/img/oyuncak/urun_63.jpg', 1, 1, 120, '3+', 'Hot Wheels', NULL),
('Mikroskop Seti (1200x)', 'Okul projeleri için bilimsel mikroskop.', 750.00, '/img/oyuncak/urun_64.jpg', 1, 0, 22, '10+', 'SciencePlay', NULL),
('Barbie Dreamtopia Denizkızı', 'Işıklı ve yüzebilen denizkızı bebek.', 580.00, '/img/oyuncak/urun_65.jpg', 0, 1, 45, '3+', 'Mattel', NULL),
('Cluedo Dedektiflik Oyunu', 'Malikanedeki katili bulma gizemi.', 520.00, '/img/oyuncak/urun_66.jpg', 0, 1, 30, '8+', 'Hasbro', NULL),
('Lego Star Wars Boba Fett', 'Kask ve sergileme standı içeren set.', 1100.00, '/img/oyuncak/urun_67.jpg', 1, 0, 10, '14+', 'LEGO', NULL),
('Pokemon Battle Figure 3-Pack', 'Pikachu ve arkadaşları figür seti.', 380.00, '/img/oyuncak/urun_68.jpg', 1, 1, 65, '4+', 'Jazwares', NULL),
('Kayıp Kelimeler Hece Oyunu', 'Okuma yazma öğrenmeye yardımcı kartlar.', 180.00, '/img/oyuncak/urun_69.jpg', 0, 1, 100, '5+', 'EğiticiDünya', NULL),
('Büyük Boy Basketbol Potası', 'İç ve dış mekan uyumlu ayaklı pota.', 1250.00, '/img/oyuncak/urun_70.jpg', 1, 0, 8, '6+', 'Sporty', NULL),
('Lego Minecraft Kale Savaşı', 'Oyun dünyasını gerçek hayata taşıyan set.', 820.00, '/img/oyuncak/urun_71.jpg', 1, 1, 20, '8+', 'LEGO', NULL),
('Barbie Gardırop Seti', 'Taşınabilir, kıyafet dolu bebek dolabı.', 950.00, '/img/oyuncak/urun_72.jpg', 0, 1, 15, '3+', 'Mattel', NULL),
('Playmobil Korsan Gemisi', 'Yüzen ve ateş edebilen korsan gemisi.', 1450.00, '/img/oyuncak/urun_73.jpg', 0, 1, 7, '4+', 'Playmobil', NULL),
('Carcassonne Strateji Oyunu', 'Ortaçağ şehir kurma harita oyunu.', 780.00, '/img/oyuncak/urun_74.jpg', 0, 1, 20, '8+', 'Z-Man Games', NULL),
('Uçan Helikopter (Sensorlü)', 'El ile kontrol edilebilen mini helikopter.', 320.00, '/img/oyuncak/urun_75.jpg', 1, 0, 50, '8+', 'TechToys', NULL),
('Disney Cars Şimşek McQueen', '30 cm metalik dev Şimşek McQueen.', 650.00, '/img/oyuncak/urun_76.jpg', 0, 1, 30, '3+', 'Mattel', NULL),
('FurReal Sevimli Ayıcık', 'Seslere tepki veren interaktif peluş.', 1100.00, '/img/oyuncak/urun_77.jpg', 1, 1, 12, '4+', 'Hasbro', NULL),
('Amiral Battı Klasik Oyunu', 'Deniz savaşı strateji oyunu.', 380.00, '/img/oyuncak/urun_78.jpg', 0, 1, 40, '7+', 'Hasbro', NULL),
('Lego Technic Kepçe', 'Pistonları çalışan iş makinesi seti.', 920.00, '/img/oyuncak/urun_79.jpg', 1, 0, 15, '9+', 'LEGO', NULL),
('Glow in the Dark Slime Kit', 'Gece parlayan slime yapım kiti.', 220.00, '/img/oyuncak/urun_80.jpg', 1, 1, 60, '5+', 'NovaFun', NULL),
('Nerf Fortnite Blaster', 'Fortnite oyunundaki özel silah kopyası.', 850.00, '/img/oyuncak/urun_81.jpg', 1, 0, 25, '8+', 'Nerf', NULL),
('Barbie Tatil Villası', 'Açılır kapanır, aksesuarlı ev.', 1350.00, '/img/oyuncak/urun_82.jpg', 1, 1, 10, '3+', 'Mattel', NULL),
('Hot Wheels Akrobasi Seti', '360 derece döngülü fırlatma seti.', 720.00, '/img/oyuncak/urun_83.jpg', 1, 1, 20, '4+', 'Hot Wheels', NULL),
('Stratego Savaş Oyunu', 'Bayrağı koruma üzerine kurulu oyun.', 480.00, '/img/oyuncak/urun_84.jpg', 0, 1, 35, '8+', 'Jumbo', NULL),
('Manyetik Bloklar 100 Parça', '3D yapılar kurmak için güçlü mıknatıslar.', 950.00, '/img/oyuncak/urun_85.jpg', 1, 1, 22, '3+', 'MagnaTiles', NULL),
('Talking Tom İnteraktif Kedi', 'Söylenenleri taklit eden konuşan kedi.', 320.00, '/img/oyuncak/urun_86.jpg', 0, 1, 55, '3+', 'Dragon-I', NULL),
('Ahşap Blok Tren', 'Harf ve rakamlı vagonlu ahşap tren.', 280.00, '/img/oyuncak/urun_87.jpg', 0, 1, 45, '18 Ay+', 'Woody', NULL),
('Okçuluk Seti (Vantuzlu)', 'Hedef tahtası ve yay takımı.', 420.00, '/img/oyuncak/urun_88.jpg', 1, 0, 30, '6+', 'Sporty', NULL),
('Barbie Spa Günü Bebek', 'Maske ve aksesuarlı kişisel bakım bebeği.', 520.00, '/img/oyuncak/urun_89.jpg', 1, 0, 25, '3+', 'Mattel', NULL),
('Lego Classic Pencereler Paketi', 'Ev tasarlamak için özel lego parçaları.', 450.00, '/img/oyuncak/urun_90.jpg', 0, 1, 50, '4+', 'LEGO', NULL),
('My Little Pony Işıklı Figür', 'Kanatları hareketli ve sesli Pony.', 350.00, '/img/oyuncak/urun_91.jpg', 1, 1, 40, '3+', 'Hasbro', NULL),
('Air Hockey Masaüstü', 'Pilli hava üflemeli hokey masası.', 650.00, '/img/oyuncak/urun_92.jpg', 1, 0, 15, '6+', 'FunGames', NULL),
('Çizim Tableti (LCD Yazı)', 'Silinebilir dijital not ve çizim tahtası.', 220.00, '/img/oyuncak/urun_93.jpg', 1, 1, 100, '3+', 'TechToys', NULL),
('Polly Pocket Şato Çantası', 'Açılınca dev dünyaya dönüşen mini çanta.', 480.00, '/img/oyuncak/urun_94.jpg', 1, 1, 30, '4+', 'Mattel', NULL),
('Hulk Aksiyon Figürü 30cm', 'Kaslı ve hareketli dev Hulk figürü.', 450.00, '/img/oyuncak/urun_95.jpg', 0, 1, 20, '4+', 'Hasbro', NULL),
('Risk Game of Thrones Edition', 'Özel seri GoT temalı strateji oyunu.', 1250.00, '/img/oyuncak/urun_96.jpg', 1, 0, 10, '16+', 'Hasbro', NULL),
('Gitar Başlangıç Seti', 'Çocuklar için gerçek telli küçük gitar.', 850.00, '/img/oyuncak/urun_97.jpg', 1, 1, 12, '8+', 'MusicStar', NULL),
('Lego Creator 3''ü 1 Arada Kuş', 'Papağan, balık veya kurbağaya dönüşür.', 320.00, '/img/oyuncak/urun_98.jpg', 1, 1, 40, '7+', 'LEGO', NULL),
('Mikado Çubukları Dev Boy', 'Odaklanma ve denge oyunu.', 150.00, '/img/oyuncak/urun_99.jpg', 0, 1, 100, '6+', 'FunGames', NULL),
('Rubik Kübü 3x3 Orijinal', 'Dünyanın en çok satan zeka küpü.', 220.00, '/img/oyuncak/urun_100.jpg', 0, 1, 150, '8+', 'Rubik', NULL);