-- 0. VARSA ESKİ GEÇİCİ TABLOYU TEMİZLE
IF OBJECT_ID('tempdb..#TempKitaplar') IS NOT NULL DROP TABLE #TempKitaplar;
GO

-- 1. KATEGORİLERİ GÜVENLE EKLE (Sadece Yoklarsa)
SET IDENTITY_INSERT [Kategoriler] ON;
IF NOT EXISTS (SELECT 1 FROM Kategoriler WHERE KategoriId = 1004) INSERT INTO Kategoriler (KategoriId, KategoriAdi, IkonSifi) VALUES (1004, 'Dünya Klasikleri', '🌍');
IF NOT EXISTS (SELECT 1 FROM Kategoriler WHERE KategoriId = 1005) INSERT INTO Kategoriler (KategoriId, KategoriAdi, IkonSifi) VALUES (1005, 'Türk Edebiyatı', '🇹🇷');
IF NOT EXISTS (SELECT 1 FROM Kategoriler WHERE KategoriId = 1006) INSERT INTO Kategoriler (KategoriId, KategoriAdi, IkonSifi) VALUES (1006, 'Bilim Kurgu & Fantastik', '🚀');
IF NOT EXISTS (SELECT 1 FROM Kategoriler WHERE KategoriId = 1007) INSERT INTO Kategoriler (KategoriId, KategoriAdi, IkonSifi) VALUES (1007, 'Polisiye & Gizem', '🕵️');
IF NOT EXISTS (SELECT 1 FROM Kategoriler WHERE KategoriId = 1008) INSERT INTO Kategoriler (KategoriId, KategoriAdi, IkonSifi) VALUES (1008, 'Felsefe & Düşünce', '🧠');
IF NOT EXISTS (SELECT 1 FROM Kategoriler WHERE KategoriId = 1009) INSERT INTO Kategoriler (KategoriId, KategoriAdi, IkonSifi) VALUES (1009, 'Kişisel Gelişim', '🌱');
SET IDENTITY_INSERT [Kategoriler] OFF;
GO

-- 2. GEÇİCİ TABLO OLUŞTUR VE VERİLERİ YÜKLE
CREATE TABLE #TempKitaplar (KitapId INT, KitapAdi NVARCHAR(255), YazarAdi NVARCHAR(255), Fiyat DECIMAL(18,2), Aciklama NVARCHAR(MAX), KategoriId INT, ResimUrl NVARCHAR(255));

INSERT INTO #TempKitaplar (KitapId, KitapAdi, YazarAdi, Fiyat, Aciklama, KategoriId, ResimUrl)
VALUES
(1180, 'Şeker Portakalı', 'Jose Mauro de Vasconcelos', 135.00, 'Küçük Zeze''nin duygusal büyüme hikayesi.', 1004, '/img/kitaplar/seker_portakali.jpg'),
(1181, 'Bülbülü Öldürmek', 'Harper Lee', 180.00, 'Adalet ve ırkçılık üzerine unutulmaz roman.', 1004, '/img/kitaplar/bulbulu_oldurmek.jpg'),
(1182, 'Çavdar Tarlasında Çocuklar', 'J.D. Salinger', 155.00, 'Gençlik bunalımı ve yabancılaşma hikayesi.', 1004, '/img/kitaplar/cavdar_tarlasinda_cocuklar.jpg'),
(1183, 'Lolita', 'Vladimir Nabokov', 190.00, 'Takıntılı bir aşkın çarpıcı anlatımı.', 1004, '/img/kitaplar/lolita.jpg'),
(1184, 'Rebecca', 'Daphne du Maurier', 165.00, 'Gotik atmosferli psikolojik gerilim romanı.', 1004, '/img/kitaplar/rebecca.jpg'),
(1185, 'Güneş de Doğar', 'Ernest Hemingway', 170.00, 'Kayıp kuşağın Avrupa macerası.', 1004, '/img/kitaplar/gunes_de_dogar.jpg'),
(1186, 'Silahlara Veda', 'Ernest Hemingway', 160.00, 'Savaşın ortasında yaşanan trajik aşk.', 1004, '/img/kitaplar/silahlara_veda.jpg'),
(1187, 'Yaşlı Adam ve Deniz', 'Ernest Hemingway', 125.00, 'Bir balıkçının doğayla mücadelesi.', 1004, '/img/kitaplar/yasli_adam_ve_deniz.jpg'),
(1188, 'Anna Frank''ın Hatıra Defteri', 'Anne Frank', 145.00, 'Savaş yıllarında bir genç kızın günlüğü.', 1004, '/img/kitaplar/anna_frank_hatira_defteri.jpg'),
(1189, 'Küçük Kadınlar', 'Louisa May Alcott', 150.00, 'Dört kız kardeşin büyüme hikayesi.', 1004, '/img/kitaplar/kucuk_kadinlar.jpg'),
(1190, 'Jane Eyre', 'Charlotte Bronte', 175.00, 'Güçlü bir kadının bağımsızlık mücadelesi.', 1004, '/img/kitaplar/jane_eyre.jpg'),
(1191, 'Emma', 'Jane Austen', 165.00, 'Evlilik ve sosyal ilişkiler üzerine klasik roman.', 1004, '/img/kitaplar/emma.jpg'),
(1192, 'Beyaz Diş', 'Jack London', 140.00, 'Vahşi doğada hayatta kalma öyküsü.', 1004, '/img/kitaplar/beyaz_dis.jpg'),
(1193, 'Vahşetin Çağrısı', 'Jack London', 135.00, 'Bir köpeğin içgüdülerine dönüş hikayesi.', 1004, '/img/kitaplar/vahsetin_cagrisi.jpg'),
(1194, 'Kızıl ve Siyah', 'Stendhal', 185.00, 'Hırs ve aşk arasında kalan genç adamın hikayesi.', 1004, '/img/kitaplar/kizil_ve_siyah.jpg'),
(1195, 'Oblomov', 'İvan Gonçarov', 170.00, 'Tembellik ve toplum eleştirisi üzerine klasik eser.', 1004, '/img/kitaplar/oblomov.jpg'),
(1196, 'Budala', 'Dostoyevski', 220.00, 'Saf iyiliğin toplumdaki yeri üzerine roman.', 1004, '/img/kitaplar/budala.jpg'),
(1197, 'Ekmek Arası', 'Charles Bukowski', 145.00, 'Zorlu bir hayatın sert anlatımı.', 1004, '/img/kitaplar/ekmek_arasi.jpg'),
(1198, 'Postane', 'Charles Bukowski', 150.00, 'Amerikan alt kültürüne mizahi bakış.', 1004, '/img/kitaplar/postane.jpg'),
(1199, 'Martin Eden', 'Jack London', 180.00, 'Yazar olma hayali kuran bir denizcinin hikayesi.', 1004, '/img/kitaplar/martin_eden.jpg'),
(1200, 'Kör Baykuş', 'Sadık Hidayet', 130.00, 'Modern İran edebiyatının kült romanı.', 1004, '/img/kitaplar/kor_baykus.jpg'),
(1201, 'Çanlar Kimin İçin Çalıyor', 'Ernest Hemingway', 190.00, 'İspanya İç Savaşı sırasında geçen dramatik roman.', 1004, '/img/kitaplar/canlar_kimin_icin_caliyor.jpg'),
(1202, 'Genç Werther''in Acıları', 'Goethe', 145.00, 'Karşılıksız aşkın trajik öyküsü.', 1004, '/img/kitaplar/genc_wertherin_acilari.jpg'),
(1203, 'Monte Kristo Kontu', 'Alexandre Dumas', 240.00, 'İhanet ve intikam üzerine epik macera.', 1004, '/img/kitaplar/monte_kristo_kontu.jpg'),
(1204, 'Üç Silahşörler', 'Alexandre Dumas', 210.00, 'Onur ve dostluk dolu şövalyelik hikayesi.', 1004, '/img/kitaplar/uc_silahsorler.jpg'),
(1205, 'Notre Dame''ın Kamburu', 'Victor Hugo', 195.00, 'Paris''te geçen dramatik aşk hikayesi.', 1004, '/img/kitaplar/notre_damein_kamburu.jpg'),
(1206, 'Denemeler', 'Montaigne', 160.00, 'İnsan doğası üzerine felsefi düşünceler.', 1008, '/img/kitaplar/denemeler.jpg'),
(1207, 'Leviathan', 'Thomas Hobbes', 175.00, 'Devlet ve toplum sözleşmesi üzerine eser.', 1008, '/img/kitaplar/leviathan.jpg'),
(1208, 'İkinci Cins', 'Simone de Beauvoir', 230.00, 'Kadın kimliği üzerine çığır açan çalışma.', 1008, '/img/kitaplar/ikinci_cins.jpg'),
(1209, 'Toplum Sözleşmesi', 'Rousseau', 140.00, 'Halk egemenliği ve özgürlük üzerine klasik eser.', 1008, '/img/kitaplar/toplum_sozlesmesi.jpg'),
(1210, 'Tractatus Logico-Philosophicus', 'Wittgenstein', 200.00, 'Dil ve mantık üzerine önemli felsefi eser.', 1008, '/img/kitaplar/tractatus.jpg'),
(1211, 'Varoluşçuluk Bir Hümanizmdir', 'Jean-Paul Sartre', 120.00, 'Varoluşçuluk felsefesinin temel açıklaması.', 1008, '/img/kitaplar/varolusculuk_bir_humanizmdir.jpg'),
(1212, 'İrade Terbiyesi', 'Jules Payot', 135.00, 'Disiplin ve çalışma alışkanlığı geliştirme rehberi.', 1009, '/img/kitaplar/irade_terbiyesi.jpg'),
(1213, 'Deep Work', 'Cal Newport', 170.00, 'Derin odaklanma ile verimli çalışma yöntemleri.', 1009, '/img/kitaplar/deep_work.jpg'),
(1214, 'Düşün ve Zengin Ol', 'Napoleon Hill', 180.00, 'Başarı ve finansal özgürlük üzerine klasik eser.', 1009, '/img/kitaplar/dusun_ve_zengin_ol.jpg'),
(1215, 'Mucize Sabahlar', 'Hal Elrod', 145.00, 'Sabah rutinleriyle hayatı değiştirme rehberi.', 1009, '/img/kitaplar/mucize_sabahlar.jpg'),
(1216, 'Akış', 'Mihaly Csikszentmihalyi', 190.00, 'Mutluluk ve üretkenlik psikolojisi üzerine çalışma.', 1009, '/img/kitaplar/akis.jpg'),
(1217, 'Outliers', 'Malcolm Gladwell', 175.00, 'Başarının görünmeyen dinamikleri.', 1009, '/img/kitaplar/outliers.jpg'),
(1218, 'Startup', 'Ben Horowitz', 210.00, 'Girişimcilik dünyasının zorlukları üzerine.', 1009, '/img/kitaplar/startup.jpg'),
(1219, 'Psikolojinin Temel İlkeleri', 'William James', 220.00, 'Psikoloji biliminin temel taşlarından biri.', 1009, '/img/kitaplar/psikolojinin_temel_ilkeleri.jpg'),
(1220, 'İyi Hissetmek', 'David Burns', 165.00, 'Bilişsel terapi teknikleriyle mutluluk rehberi.', 1009, '/img/kitaplar/iyi_hissetmek.jpg'),
(1221, 'Morgue Sokağı Cinayetleri', 'Edgar Allan Poe', 130.00, 'Modern dedektif hikayelerinin başlangıcı.', 1007, '/img/kitaplar/morgue_sokagi.jpg'),
(1222, 'Malta Şahini', 'Dashiell Hammett', 145.00, 'Kara roman türünün öncü eserlerinden biri.', 1007, '/img/kitaplar/malta_sahini.jpg'),
(1223, 'Büyük Uyku', 'Raymond Chandler', 150.00, 'Özel dedektif Philip Marlowe''un ilk macerası.', 1007, '/img/kitaplar/buyuk_uyku.jpg'),
(1224, 'Gülün Adı', 'Umberto Eco', 240.00, 'Orta Çağ manastırında geçen gizemli cinayetler.', 1007, '/img/kitaplar/gulun_adi.jpg'),
(1225, 'Kaybolan Sembol', 'Dan Brown', 220.00, 'Masonluk ve sembollerle dolu gerilim romanı.', 1007, '/img/kitaplar/kaybolan_sembol.jpg'),
(1226, 'Ölüm Sessiz Geldi', 'Michael Connelly', 185.00, 'Polisiye ve suç dünyasında sürükleyici hikaye.', 1007, '/img/kitaplar/olum_sessiz_geldi.jpg'),
(1227, 'Kemik Koleksiyoncusu', 'Jeffery Deaver', 195.00, 'Zeki bir seri katilin izini süren dedektifler.', 1007, '/img/kitaplar/kemik_koleksiyoncusu.jpg'),
(1228, 'Kara Kule', 'Stephen King', 260.00, 'Fantastik ve korku öğelerini birleştiren seri.', 1007, '/img/kitaplar/kara_kule.jpg'),
(1229, 'Medyum', 'Stephen King', 170.00, 'Doğaüstü güçlerle çevrili gerilim hikayesi.', 1007, '/img/kitaplar/medyum.jpg'),
(1230, 'Moby Dick', 'Herman Melville', 195.00, 'Kaptan Ahab''ın beyaz balina takıntısı.', 1004, '/img/kitaplar/moby_dick.jpg'),
(1231, 'Gurur ve Önyargı', 'Jane Austen', 175.00, 'Aşk, gurur ve toplumsal sınıf çatışmaları.', 1004, '/img/kitaplar/gurur_ve_onyargi.jpg'),
(1232, 'Uğultulu Tepeler', 'Emily Bronte', 165.00, 'Tutkulu ve trajik bir aşk hikayesi.', 1004, '/img/kitaplar/ugultulu_tepeler.jpg'),
(1233, 'Simurg', 'Hermann Hesse', 170.00, 'Kendini keşfetme yolculuğu.', 1008, '/img/kitaplar/simurg.jpg'),
(1234, 'Bozkırkurdu', 'Hermann Hesse', 175.00, 'Modern insanın içsel çatışmaları.', 1008, '/img/kitaplar/bozkirkurdu.jpg'),
(1235, 'Martı', 'Richard Bach', 95.00, 'Özgürlük ve kendini geliştirme üzerine alegori.', 1009, '/img/kitaplar/marti.jpg'),
(1236, 'Robinson Crusoe', 'Daniel Defoe', 140.00, 'Issız adada hayatta kalma mücadelesi.', 1004, '/img/kitaplar/robinson_crusoe.jpg'),
(1237, 'Define Adası', 'Robert Louis Stevenson', 130.00, 'Korsanlar ve hazine avı macerası.', 1007, '/img/kitaplar/define_adasi.jpg'),
(1238, 'Tom Sawyer''ın Maceraları', 'Mark Twain', 120.00, 'Yaramaz bir çocuğun eğlenceli maceraları.', 1007, '/img/kitaplar/tom_sawyer.jpg'),
(1239, 'Huckleberry Finn', 'Mark Twain', 125.00, 'Amerika nehirlerinde geçen özgürlük yolculuğu.', 1007, '/img/kitaplar/huckleberry_finn.jpg'),
(1240, 'Denizler Altında 20 Bin Fersah', 'Jules Verne', 175.00, 'Kaptan Nemo ile denizaltı macerası.', 1006, '/img/kitaplar/denizler_altinda.jpg'),
(1241, 'Seksen Günde Devri Alem', 'Jules Verne', 160.00, 'Dünya turuna çıkan bir adamın yarışı.', 1006, '/img/kitaplar/seksen_gunde.jpg'),
(1242, 'Pal Sokağı Çocukları', 'Ferenc Molnar', 115.00, 'Çocukluk dostluğu ve mahalle mücadelesi.', 1007, '/img/kitaplar/pal_sokagi.jpg'),
(1243, 'Sineklerin Tanrısı', 'William Golding', 155.00, 'Medeniyetten uzak kalan çocukların vahşileşmesi.', 1004, '/img/kitaplar/sineklerin_tanrisi.jpg'),
(1244, 'Gece Yarısı Çocukları', 'Salman Rushdie', 210.00, 'Hindistan''ın bağımsızlığıyla doğan çocukların hikayesi.', 1004, '/img/kitaplar/gece_yarisi_cocuklari.jpg'),
(1245, 'Bin Muhteşem Güneş', 'Khaled Hosseini', 190.00, 'Afganistan''da iki kadının dramatik yaşamı.', 1004, '/img/kitaplar/bin_muhtesem_gunes.jpg'),
(1246, 'Uçurtma Avcısı', 'Khaled Hosseini', 185.00, 'Dostluk, ihanet ve kefaret üzerine roman.', 1004, '/img/kitaplar/ucurtma_avcisi.jpg'),
(1247, 'Pi''nin Yaşamı', 'Yann Martel', 170.00, 'Bir çocuk ve kaplanın okyanustaki hayatta kalma mücadelesi.', 1004, '/img/kitaplar/pinin_yasami.jpg'),
(1248, 'Zorba', 'Nikos Kazancakis', 160.00, 'Özgür ruhlu bir adamın hayat felsefesi.', 1004, '/img/kitaplar/zorba.jpg'),
(1249, 'Bir İdam Mahkumunun Son Günü', 'Victor Hugo', 130.00, 'Ölüm cezasına karşı etkileyici bir anlatım.', 1004, '/img/kitaplar/bir_idam_mahkumunun_son_gunu.jpg'),
(1250, 'Saatleri Durdurma Enstitüsü', 'José Saramago', 180.00, 'Zaman ve insan ilişkileri üzerine düşündüren roman.', 1004, '/img/kitaplar/saatleri_durdurma.jpg'),
(1251, 'Satranç', 'Stefan Zweig', 120.00, 'Psikolojik gerilim dolu kısa roman.', 1004, '/img/kitaplar/satranc.jpg'),
(1252, 'Ayaklanma', 'Albert Camus', 145.00, 'İnsan özgürlüğü ve başkaldırı üzerine deneme.', 1008, '/img/kitaplar/ayaklanma.jpg'),
(1253, 'Felsefenin Tesellisi', 'Alain de Botton', 165.00, 'Felsefeyi günlük yaşama uyarlayan eser.', 1008, '/img/kitaplar/felsefenin_tesellisi.jpg'),
(1254, 'Korku ve Titreme', 'Soren Kierkegaard', 175.00, 'İnanç ve etik üzerine derin düşünceler.', 1008, '/img/kitaplar/korku_ve_titreme.jpg'),
(1255, 'Devlet Adamı', 'Cicero', 140.00, 'Siyaset ve erdem üzerine klasik eser.', 1008, '/img/kitaplar/devlet_adami.jpg'),
(1256, 'Mutlu Yaşam Üzerine', 'Seneca', 135.00, 'Stoacı yaşam felsefesinin temel taşlarından biri.', 1008, '/img/kitaplar/mutlu_yasam.jpg'),
(1257, 'İnsan Neyle Yaşar', 'Lev Tolstoy', 110.00, 'İnsan sevgisi ve merhamet üzerine öyküler.', 1008, '/img/kitaplar/insan_neyle_yasar.jpg'),
(1258, 'Minimalizm', 'Joshua Fields Millburn', 155.00, 'Sade yaşamın gücü üzerine modern rehber.', 1009, '/img/kitaplar/minimalizm.jpg'),
(1259, 'Alışkanlıkların Gücü', 'Charles Duhigg', 175.00, 'Alışkanlıkların hayatımızı nasıl şekillendirdiği.', 1009, '/img/kitaplar/aliskanliklarin_gucu.jpg'),
(1260, 'Tek Şey', 'Gary Keller', 160.00, 'Odaklanarak başarıya ulaşmanın yolları.', 1009, '/img/kitaplar/tek_sey.jpg'),
(1261, '4 Saatlik Çalışma Haftası', 'Tim Ferriss', 185.00, 'Verimli çalışma ve özgür yaşam rehberi.', 1009, '/img/kitaplar/4_saatlik_calisma.jpg'),
(1262, 'Asla Yalnız Yeme', 'Keith Ferrazzi', 145.00, 'İnsan ilişkileri ve network kurma sanatı.', 1009, '/img/kitaplar/asla_yalniz_yeme.jpg'),
(1263, 'Yapay Zeka 2041', 'Kai-Fu Lee', 220.00, 'Gelecekte yapay zekanın dünyayı nasıl değiştireceği.', 1009, '/img/kitaplar/yapay_zeka_2041.jpg'),
(1264, 'Beden Kayıt Tutar', 'Bessel van der Kolk', 230.00, 'Travma ve insan psikolojisi üzerine çalışma.', 1009, '/img/kitaplar/beden_kayit_tutar.jpg'),
(1265, 'Empati', 'Roman Krznaric', 150.00, 'İnsan ilişkilerinde empati kurmanın önemi.', 1009, '/img/kitaplar/empati.jpg'),
(1266, 'Kayıp Sembol', 'Dan Brown', 215.00, 'Gizem ve sembollerle dolu sürükleyici macera.', 1007, '/img/kitaplar/kayip_sembol.jpg'),
(1267, 'Kanun Benim', 'Mickey Spillane', 135.00, 'Sert polisiye türünün dikkat çeken eserlerinden biri.', 1007, '/img/kitaplar/kanun_benim.jpg'),
(1268, 'Şeytan Ayrıntıda Gizlidir', 'Jeffery Deaver', 190.00, 'İpucu avıyla ilerleyen gerilim dolu polisiye.', 1007, '/img/kitaplar/seytan_ayrintida.jpg'),
(1269, 'Karanlık Yerler', 'Gillian Flynn', 175.00, 'Geçmişin sırlarıyla yüzleşen bir kadının hikayesi.', 1007, '/img/kitaplar/karanlik_yerler.jpg'),
(1270, 'Trendeki Kız', 'Paula Hawkins', 180.00, 'Gizemli bir kayboluşun psikolojik çözümlemesi.', 1007, '/img/kitaplar/trendeki_kiz.jpg'),
(1271, 'Sessiz Hasta', 'Alex Michaelides', 195.00, 'Konuşmayı bırakan bir kadının gizemi.', 1007, '/img/kitaplar/sessiz_hasta.jpg'),
(1272, 'Cinayet Alfabesi', 'Sue Grafton', 150.00, 'Alfabetik seri cinayetlerin izini süren dedektif.', 1007, '/img/kitaplar/cinayet_alfabesi.jpg'),
(1273, 'Kızıl Nehirler', 'Jean-Christophe Grange', 210.00, 'Fransız Alplerinde geçen karanlık cinayet hikayesi.', 1007, '/img/kitaplar/kizil_nehirler.jpg'),
(1274, 'Ölü Ruhlar Kulübü', 'Charlaine Harris', 165.00, 'Doğaüstü olaylarla örülü polisiye roman.', 1007, '/img/kitaplar/olu_ruhlar.jpg'),
(1275, 'Baskerville Tazısı', 'Arthur Conan Doyle', 145.00, 'Sherlock Holmes''un en ünlü vakalarından biri.', 1007, '/img/kitaplar/baskerville.jpg'),
(1276, 'The Great Gatsby', 'F. Scott Fitzgerald', 165.00, 'Batı toplumunun parıltılı ama boş yaşam eleştirisi.', 1004, '/img/kitaplar/great_gatsby.jpg'),
(1277, 'Yüzyıllık Yalnızlık', 'Gabriel García Márquez', 210.00, 'Buendia ailesinin nesiller boyu süren büyülü hikayesi.', 1004, '/img/kitaplar/yuzyillik_yalnizlik.jpg'),
(1278, 'Dava', 'Franz Kafka', 150.00, 'Anlam verilemeyen bir suçlama karşısında bireyin çaresizliği.', 1004, '/img/kitaplar/dava.jpg'),
(1279, 'Dune Mesihi', 'Frank Herbert', 195.00, 'Paul Atreides’in imparatorluk sonrası yaşadığı içsel ve politik çatışmalar.', 1006, '/img/kitaplar/dune_mesihi.jpg'),
(1280, 'Yabancı', 'Albert Camus', 115.00, 'Absürdizmin ve yabancılaşmanın başyapıtı.', 1004, '/img/kitaplar/yabanci.jpg'),
(1281, 'Dönüşüm', 'Franz Kafka', 95.00, 'Gregor Samsa''nın bir sabah böceğe dönüşme hikayesi.', 1004, '/img/kitaplar/donusum.jpg'),
(1282, 'Beyaz Geceler', 'Dostoyevski', 105.00, 'St. Petersburg''da geçen hüzünlü bir hayalperest öyküsü.', 1004, '/img/kitaplar/beyaz_geceler.jpg'),
(1283, 'Kumarbaz', 'Dostoyevski', 130.00, 'Tutku ve irade çatışması üzerine sarsıcı bir roman.', 1004, '/img/kitaplar/kumarbaz.jpg'),
(1284, 'İnsancıklar', 'Dostoyevski', 110.00, 'Dostoyevski''nin ilk romanı ve toplumsal dram.', 1004, '/img/kitaplar/insanciklar.jpg'),
(1285, 'Ölüler Evinden Anılar', 'Dostoyevski', 155.00, 'Sibirya''daki hapishane hayatının gerçekçi anlatımı.', 1004, '/img/kitaplar/oluler_evinden.jpg'),
(1286, 'Müfettiş', 'Nikolay Gogol', 100.00, 'Bürokrasi ve yolsuzluk üzerine sert bir yergi.', 1004, '/img/kitaplar/mufettis.jpg'),
(1287, 'Şato', 'Franz Kafka', 170.00, 'Ulaşılamayan otorite ve bürokratik labirentler.', 1004, '/img/kitaplar/sato.jpg'),
(1288, 'Milena''ya Mektuplar', 'Franz Kafka', 140.00, 'Edebiyat tarihinin en derinlikli aşk mektupları.', 1004, '/img/kitaplar/milenaya_mektuplar.jpg'),
(1289, 'Dr. Jekyll ve Mr. Hyde', 'R. L. Stevenson', 115.00, 'İnsan doğasındaki iyi ve kötünün savaşı.', 1004, '/img/kitaplar/dr_jekyll.jpg'),
(1290, 'Dorian Gray''in Portresi', 'Oscar Wilde', 150.00, 'Güzellik, gençlik ve ahlaki çöküşün romanı.', 1004, '/img/kitaplar/dorian_gray.jpg'),
(1291, 'Mutlu Prens', 'Oscar Wilde', 90.00, 'Fedakarlık ve iyilik üzerine etkileyici masallar.', 1004, '/img/kitaplar/mutlu_prens.jpg'),
(1292, 'Oliver Twist', 'Charles Dickens', 160.00, 'Yetimhaneden sokaklara uzanan bir hayatta kalma öyküsü.', 1004, '/img/kitaplar/oliver_twist.jpg'),
(1293, 'İki Şehrin Hikayesi', 'Charles Dickens', 175.00, 'Fransız Devrimi gölgesinde kaos ve aşk.', 1004, '/img/kitaplar/iki_sehrin_hikayesi.jpg'),
(1294, 'Büyük Umutlar', 'Charles Dickens', 180.00, 'Pip''in çocukluğundan yetişkinliğine uzanan sancılı büyüme hikayesi.', 1004, '/img/kitaplar/buyuk_umutlar.jpg'),
(1295, 'Gulliver''in Gezileri', 'Jonathan Swift', 130.00, 'İnsan doğasına ve topluma yönelik keskin bir eleştiri.', 1004, '/img/kitaplar/gulliver.jpg'),
(1296, 'Küçük Prens', 'Antoine de Saint-Exupery', 85.00, 'Çocukların gözünden büyüklerin dünyası.', 1004, '/img/kitaplar/kucuk_prens.jpg'),
(1297, 'On Bir Dakika', 'Paulo Coelho', 155.00, 'Aşk ve cinsellik üzerine provokatif bir anlatı.', 1004, '/img/kitaplar/on_bir_dakika.jpg'),
(1298, 'Veronika Ölmek İstiyor', 'Paulo Coelho', 145.00, 'Yaşamın anlamını sorgulayan bir delilik hikayesi.', 1004, '/img/kitaplar/veronika.jpg'),
(1299, 'Körlük', 'Jose Saramago', 190.00, 'Bilinmeyen bir körlük salgınının yarattığı toplumsal kaos.', 1004, '/img/kitaplar/korluk.jpg'),
(1300, 'Görmek', 'Jose Saramago', 185.00, 'Demokrasi ve siyaset üzerine alegorik bir roman.', 1004, '/img/kitaplar/gormek.jpg'),
(1301, 'Veba', 'Albert Camus', 165.00, 'Salgın hastalık karşısında insanlık ve dayanışma.', 1004, '/img/kitaplar/veba.jpg'),
(1302, 'Mutlu Ölüm', 'Albert Camus', 125.00, 'Mutluluğu arayan bir adamın felsefi yolculuğu.', 1004, '/img/kitaplar/mutlu_olum.jpg'),
(1303, 'Fareler ve İnsanlar', 'John Steinbeck', 110.00, 'Büyük Buhran döneminde iki arkadaşın dokunaklı hikayesi.', 1004, '/img/kitaplar/fareler_ve_insanlar.jpg'),
(1304, 'Gazap Üzümleri', 'John Steinbeck', 220.00, 'Topraklarından koparılan mevsimlik işçilerin dramı.', 1004, '/img/kitaplar/gazap_uzumleri.jpg'),
(1305, 'İnci', 'John Steinbeck', 100.00, 'Büyük bir inci bulan balıkçının trajedisi.', 1004, '/img/kitaplar/inci.jpg'),
(1306, 'Dr. Moreau''nun Adası', 'H.G. Wells', 135.00, 'Bilimsel deneyler ve canavarlığa dönüşüm.', 1006, '/img/kitaplar/dr_moreau.jpg'),
(1307, 'Dünyalar Savaşı', 'H.G. Wells', 150.00, 'Marslıların dünyayı istilası üzerine klasik bilim kurg.', 1006, '/img/kitaplar/dunyalar_savasi.jpg'),
(1308, 'Görünmez Adam', 'H.G. Wells', 120.00, 'Görünmezliği bulan bir bilim insanının yalnızlığı.', 1006, '/img/kitaplar/gorunmez_adam.jpg'),
(1309, 'Ben, Robot', 'Isaac Asimov', 170.00, 'Robotik yasaları ve yapay zeka öyküleri.', 1006, '/img/kitaplar/ben_robot.jpg'),
(1310, 'Vakıf ve İmparatorluk', 'Isaac Asimov', 185.00, 'Galaktik İmparatorluğun kaderini belirleyen savaşlar.', 1006, '/img/kitaplar/vakif.jpg'),
(1311, 'İkinci Vakıf', 'Isaac Asimov', 185.00, 'Psiko-tarih biliminin gizli koruyucuları.', 1006, '/img/kitaplar/ikinci_vakif.jpg'),
(1312, 'Çocukluğun Sonu', 'Arthur C. Clarke', 160.00, 'Dünya dışı üstün bir ırkın insanlığa müdahalesi.', 1006, '/img/kitaplar/cocuklugun_sonu.jpg'),
(1313, '2001: Bir Uzay Destanı', 'Arthur C. Clarke', 175.00, 'İnsanın evrimine ve geleceğine dair epik yolculuk.', 1006, '/img/kitaplar/2001_uzay.jpg'),
(1314, 'Kaplan! Kaplan!', 'Alfred Bester', 155.00, 'Işınlanma ve intikam temalı siberpunk öncüsü.', 1006, '/img/kitaplar/kaplan_kaplan.jpg'),
(1315, 'Mülksüzler', 'Ursula K. Le Guin', 180.00, 'Anarşist bir ütopya ile kapitalist dünyanın kıyaslanması.', 1006, '/img/kitaplar/mulksuzler.jpg'),
(1316, 'Yerdeniz Büyücüsü', 'Ursula K. Le Guin', 165.00, 'Büyü, isimler ve gölgeler üzerine fantastik bir klasik.', 1006, '/img/kitaplar/yerdeniz_buyucusu.jpg'),
(1317, 'Otomatik Portakal', 'Anthony Burgess', 145.00, 'Şiddet, özgür irade ve devlet kontrolü.', 1006, '/img/kitaplar/otomatik_portakal.jpg'),
(1318, 'Damızlık Kızın Öyküsü', 'Margaret Atwood', 190.00, 'Kadınların sadece damızlık olarak görüldüğü karanlık gelecek.', 1006, '/img/kitaplar/damizlik_kiz.jpg'),
(1319, 'Maymunlar Gezegeni', 'Pierre Boulle', 140.00, 'İnsan ve maymun rollerinin değiştiği şaşırtıcı gezegen.', 1006, '/img/kitaplar/maymunlar_gezegeni.jpg'),
(1320, 'Frankenstein', 'Mary Shelley', 150.00, 'Yaratıcısına isyan eden bir canavarın trajik öyküsü.', 1004, '/img/kitaplar/frankenstein.jpg'),
(1321, 'Dracula', 'Bram Stoker', 170.00, 'Transilvanya''dan Londra''ya uzanan gotik korku.', 1004, '/img/kitaplar/dracula.jpg'),
(1322, 'Kızıl Soruşturma', 'Sir Arthur Conan Doyle', 125.00, 'Sherlock Holmes ve Watson''ın çözdüğü ilk dava.', 1007, '/img/kitaplar/kizil_sorusturma.jpg'),
(1323, 'Dörtlerin İmzası', 'Sir Arthur Conan Doyle', 130.00, 'Kayıp hazine ve gizemli bir intikam hikayesi.', 1007, '/img/kitaplar/dortlerin_imzasi.jpg'),
(1324, 'Nil''de Ölüm', 'Agatha Christie', 160.00, 'Lüks bir gemide işlenen ustaca kurgulanmış cinayet.', 1007, '/img/kitaplar/nilde_olum.jpg'),
(1325, 'Roger Ackroyd Cinayeti', 'Agatha Christie', 155.00, 'Polisiye tarihinin en şaşırtıcı sonlarından biri.', 1007, '/img/kitaplar/roger_ackroyd.jpg'),
(1326, 'Cesetler Merdiveni', 'Agatha Christie', 145.00, 'Jane Marple''ın keskin zekasıyla çözülen sırlar.', 1007, '/img/kitaplar/cesetler_merdiveni.jpg'),
(1327, 'Uyuyan Ölüm', 'Agatha Christie', 140.00, 'Geçmişten gelen bir cinayetin ürpertici izleri.', 1007, '/img/kitaplar/uyuyan_olum.jpg'),
(1328, 'Gece Yarısı Kütüphanesi', 'Matt Haig', 165.00, 'Yaşanmamış hayatlar arasında bir seçim yolculuğu.', 1004, '/img/kitaplar/gece_yarisi_kutuphanesi.jpg'),
(1329, 'Mai ve Siyah', 'Halid Ziya Uşaklıgil', 150.00, 'Türk edebiyatında modern romanın başlangıcı.', 1005, '/img/kitaplar/mai_ve_siyah.jpg'),
(1330, 'Eylül', 'Mehmet Rauf', 140.00, 'Edebiyatımızın ilk psikolojik romanı.', 1005, '/img/kitaplar/eylul.jpg'),
(1331, 'Fatih-Harbiye', 'Peyami Safa', 125.00, 'Doğu-Batı çatışması ve kültürel ikilem.', 1005, '/img/kitaplar/fatih_harbiye.jpg'),
(1332, 'Matmazel Noraliya''nın Koltuğu', 'Peyami Safa', 145.00, 'Mistisizm ve realizm arasında bir arayış hikayesi.', 1005, '/img/kitaplar/matmazel_noraliya.jpg'),
(1333, 'Bir Gün Tek Başına', 'Vedat Türkali', 210.00, '27 Mayıs öncesi Türkiye''nin siyasi ve sosyal portresi.', 1005, '/img/kitaplar/bir_gun_tek_basina.jpg'),
(1334, 'Devlet Ana', 'Kemal Tahir', 220.00, 'Osmanlı Devleti''nin kuruluş dönemine epik bir bakış.', 1005, '/img/kitaplar/devlet_ana.jpg'),
(1335, 'Yorgun Savaşçı', 'Kemal Tahir', 200.00, 'Milli Mücadele döneminin zorlu şartları ve insanları.', 1005, '/img/kitaplar/yorgun_savasci.jpg'),
(1336, 'Aylak Adam', 'Yusuf Atılgan', 135.00, 'Modern şehir hayatında bireyin yalnızlığı ve yabancılaşması.', 1005, '/img/kitaplar/aylak_adam.jpg'),
(1337, 'Anayurt Oteli', 'Yusuf Atılgan', 130.00, 'Zebercet''in iç dünyasındaki karanlık ve yalnızlık.', 1005, '/img/kitaplar/anayurt_oteli.jpg'),
(1338, 'Korkuyu Beklerken', 'Oğuz Atay', 160.00, 'Bireyin iç dünyasını yansıtan sarsıcı öyküler.', 1005, '/img/kitaplar/korkuyu_beklerken.jpg'),
(1339, 'Tehlikeli Oyunlar', 'Oğuz Atay', 240.00, 'Gerçekle hayalin birbirine karıştığı modern bir roman.', 1005, '/img/kitaplar/tehlikeli_oyunlar.jpg'),
(1340, 'Sırça Köşk', 'Sabahattin Ali', 115.00, 'Toplumsal eleştiri içeren çarpıcı öyküler ve masallar.', 1005, '/img/kitaplar/sirca_kosk.jpg'),
(1341, 'Değirmen', 'Sabahattin Ali', 110.00, 'Sabahattin Ali''nin ilk öykü kitabı ve aşk hikayeleri.', 1005, '/img/kitaplar/degirmen.jpg'),
(1342, 'Yeni Dünya', 'Sabahattin Ali', 110.00, 'Anadolu insanının yaşamına ışık tutan gerçekçi öyküler.', 1005, '/img/kitaplar/yeni_dunya.jpg'),
(1343, 'Hanımın Çiftliği', 'Orhan Kemal', 175.00, 'Çukurova''da ağalık düzeni ve sınıf çatışmaları.', 1005, '/img/kitaplar/hanimin_ciftligi.jpg'),
(1344, 'Murtaza', 'Orhan Kemal', 160.00, 'Görevine sadık bir bekçinin trajikomik hikayesi.', 1005, '/img/kitaplar/murtaza.jpg'),
(1345, 'Bereketli Topraklar Üzerinde', 'Orhan Kemal', 170.00, 'Tarım işçilerinin zorlu yaşam savaşı.', 1005, '/img/kitaplar/bereketli_topraklar.jpg'),
(1346, 'Kaplumbağalar', 'Fakir Baykurt', 150.00, 'Köy hayatı ve imece ruhu üzerine bir başyapıt.', 1005, '/img/kitaplar/kaplumbagalar.jpg'),
(1347, 'Yılanların Öcü', 'Fakir Baykurt', 145.00, 'Toprak kavgası ve köylünün hak arama mücadelesi.', 1005, '/img/kitaplar/yilanlarin_ocu.jpg'),
(1348, 'Kendime Düşünceler', 'Marcus Aurelius', 140.00, 'Stoacı imparatorun yaşam ve ölüm üzerine notları.', 1008, '/img/kitaplar/kendime_dusunceler.jpg'),
(1349, 'Nutuk', 'Mustafa Kemal Atatürk', 250.00, 'Türkiye Cumhuriyeti''nin kuruluş belgesi ve tarihi söylev.', 1005, '/img/kitaplar/nutuk.jpg'),
(1350, 'Savaş Sanatı', 'Sun Tzu', 95.00, 'Strateji ve liderlik üzerine binlerce yıllık rehber.', 1008, '/img/kitaplar/savas_sanati.jpg'),
(1351, 'Mesnevi''den Seçmeler', 'Mevlana', 180.00, 'Tasavvuf felsefesinin en önemli hikmet dolu eseri.', 1008, '/img/kitaplar/mesnevi.jpg'),
(1352, 'Rubailer', 'Ömer Hayyam', 120.00, 'Hayat, şarap ve varoluş üzerine felsefi dörtlükler.', 1008, '/img/kitaplar/rubailer.jpg'),
(1353, 'Hiçliğin Mutluluğu', 'Arthur Schopenhauer', 130.00, 'Karamsar felsefenin yaşam bilgeliği üzerine yorumları.', 1008, '/img/kitaplar/hicligin_mutlulugu.jpg'),
(1354, 'İyinin ve Kötünün Ötesinde', 'Friedrich Nietzsche', 165.00, 'Geleneksel ahlakın ve değerlerin yıkımı.', 1008, '/img/kitaplar/iyinin_ve_kotunun.jpg'),
(1355, 'Ecce Homo', 'Friedrich Nietzsche', 150.00, 'Nietzsche''nin kendi felsefesini ve hayatını anlattığı eser.', 1008, '/img/kitaplar/ecce_homo.jpg'),
(1356, 'Putların Alacakaranlığı', 'Friedrich Nietzsche', 140.00, 'Batı felsefesine ve değerlerine sert bir meydan okuyuş.', 1008, '/img/kitaplar/putlarin_alacakaranligi.jpg'),
(1357, 'Şölen', 'Platon', 125.00, 'Aşk ve sevgi üzerine yapılmış felsefi tartışmalar.', 1008, '/img/kitaplar/solen.jpg'),
(1358, 'Phaidon', 'Platon', 120.00, 'Ruhun ölümsüzlüğü üzerine Sokrates''in son konuşması.', 1008, '/img/kitaplar/phaidon.jpg'),
(1359, 'Gorgias', 'Platon', 135.00, 'Retorik, güç ve adalet üzerine bir diyalog.', 1008, '/img/kitaplar/gorgias.jpg'),
(1360, 'Nikomakhos''a Etik', 'Aristoteles', 190.00, 'Mutluluk ve erdemli bir yaşamın temelleri.', 1008, '/img/kitaplar/etik.jpg'),
(1361, 'Politika', 'Aristoteles', 180.00, 'Devlet yönetimi ve toplumsal düzen üzerine inceleme.', 1008, '/img/kitaplar/politika.jpg'),
(1362, 'Ruh Üzerine', 'Aristoteles', 160.00, 'Canlılık, algı ve akıl üzerine felsefi analiz.', 1008, '/img/kitaplar/ruh_uzerine.jpg'),
(1363, '5 AM Kulübü', 'Robin Sharma', 175.00, 'Sabah erken kalkmanın verimlilik üzerindeki gücü.', 1009, '/img/kitaplar/5_am_kulubu.jpg'),
(1364, 'Ferrari''sini Satan Bilge', 'Robin Sharma', 155.00, 'Maddi dünyadan ruhsal huzura giden bir yol haritası.', 1009, '/img/kitaplar/ferrarisini_satan_bilge.jpg'),
(1365, 'Dört Anlaşma', 'Don Miguel Ruiz', 130.00, 'Toltek bilgeliği ile kişisel özgürlük rehberi.', 1009, '/img/kitaplar/dort_anlasma.jpg'),
(1366, 'Şimdinin Gücü', 'Eckhart Tolle', 180.00, 'Zihnin karmaşasından kurtulup anı yaşama sanatı.', 1009, '/img/kitaplar/simdinin_gucu.jpg'),
(1367, 'Kafaya Takmama Sanatı', 'Mark Manson', 160.00, 'Hayatı daha anlamlı kılmak için neleri dert etmeli.', 1009, '/img/kitaplar/kafaya_takmama_sanati.jpg'),
(1368, 'Yabancılarla Konuşmak', 'Malcolm Gladwell', 185.00, 'Tanımadığımız insanları neden yanlış anlarız?', 1009, '/img/kitaplar/yabancilarla_konusmak.jpg'),
(1369, 'Düşünce Gücüyle Tedavi', 'Louise Hay', 145.00, 'Olumlu düşüncelerin sağlık üzerindeki etkileri.', 1009, '/img/kitaplar/dusunce_gucuyle_tedavi.jpg'),
(1370, 'Akıllı Yatırımcı', 'Benjamin Graham', 250.00, 'Değer yatırımı üzerine finans dünyasının kutsal kitabı.', 1009, '/img/kitaplar/akilli_yatirimci.jpg'),
(1371, 'Elon Musk', 'Ashlee Vance', 220.00, 'Geleceği şekillendiren bir girişimcinin biyografisi.', 1009, '/img/kitaplar/elon_musk.jpg'),
(1372, 'Steve Jobs', 'Walter Isaacson', 230.00, 'Apple''ın kurucusunun hayatı ve teknoloji vizyonu.', 1009, '/img/kitaplar/steve_jobs.jpg'),
(1373, 'Leonardo da Vinci', 'Walter Isaacson', 240.00, 'Tarihin en meraklı dehasının hayat hikayesi.', 1009, '/img/kitaplar/leonardo_da_vinci.jpg'),
(1374, 'Homo Deus', 'Yuval Noah Harari', 210.00, 'Yarının kısa bir tarihi ve insanlığın geleceği.', 1009, '/img/kitaplar/homo_deus.jpg'),
(1375, '21. Yüzyıl İçin 21 Ders', 'Yuval Noah Harari', 200.00, 'Günümüz dünyasının en acil sorularına cevaplar.', 1009, '/img/kitaplar/21_ders.jpg'),
(1376, 'Zen ve Motosiklet Bakım Sanatı', 'Robert Pirsig', 195.00, 'Nitelik kavramı üzerine felsefi bir yolculuk.', 1008, '/img/kitaplar/zen_ve_motosiklet.jpg'),
(1377, 'İrade Gücü', 'Roy Baumeister', 170.00, 'Özdenetim ve iradenin bilimsel temelleri.', 1009, '/img/kitaplar/irade_gucu.jpg'),
(1378, 'Görünmez Kentler', 'Italo Calvino', 150.00, 'Hayali şehirler üzerinden bir rüya anlatısı.', 1004, '/img/kitaplar/gorunmez_kentler.jpg'),
(1379, 'Dune Çocukları', 'Frank Herbert', 215.00, 'Dune serisinin devamı; imparatorluk ve kader.', 1006, '/img/kitaplar/dune_cocuklari.jpg');
GO

-- 3. SİSTEMDE OLMAYAN YAZARLARI OTOMATİK OLARAK EKLE
INSERT INTO Yazarlar (AdSoyad)
SELECT DISTINCT YazarAdi 
FROM #TempKitaplar 
WHERE YazarAdi NOT IN (SELECT AdSoyad FROM Yazarlar);
GO

-- 4. KİTAPLARI ASIL TABLOYA YAZAR VE KATEGORİ BAĞLANTISIYLA AKTAR
-- ** BU KISIM GÜNCELLENDİ (Zaten Varsa Eklemez) **
SET IDENTITY_INSERT Kitaplar ON;

INSERT INTO Kitaplar (KitapId, KitapAdi, YazarId, KategoriId, Fiyat, KapakResimUrl, Aciklama, StokAdedi, YeniCikanMi, CokSatanMi)
SELECT 
    t.KitapId, 
    t.KitapAdi, 
    y.YazarId, 
    t.KategoriId, 
    t.Fiyat, 
    t.ResimUrl, 
    t.Aciklama, 
    50, -- Başlangıç olarak hepsine 50 stok veriyoruz
    1,  -- Yeni Çıkan vitrininde görünsün
    1   -- Çok Satan vitrininde görünsün
FROM #TempKitaplar t
INNER JOIN Yazarlar y ON t.YazarAdi = y.AdSoyad
WHERE NOT EXISTS (SELECT 1 FROM Kitaplar k WHERE k.KitapId = t.KitapId);

SET IDENTITY_INSERT Kitaplar OFF;
GO

-- 5. GEÇİCİ TABLOYU SİL
DROP TABLE #TempKitaplar;
GO