USE NovaKitapDB;
GO

-- 1. Tabloya yeni sütunları ekliyoruz
ALTER TABLE Kitaplar ADD Yayinevi NVARCHAR(150) NULL;
ALTER TABLE Kitaplar ADD BasimYili INT NULL;
GO

-- 2. 50 Kitap için Gerçek Özet, Yayınevi ve Basım Yılı Güncellemeleri
UPDATE Kitaplar SET Yayinevi = 'İş Bankası Kültür Yayınları', BasimYili = 1866, Aciklama = 'Fakir bir öğrenci olan Raskolnikov''un işlediği cinayet sonrası yaşadığı derin vicdan azabı ve psikolojik buhranı anlatan, insan ruhunun karanlık dehlizlerine inen eşsiz bir başyapıt.' WHERE KitapAdi = 'Suç ve Ceza';
UPDATE Kitaplar SET Yayinevi = 'İş Bankası Kültür Yayınları', BasimYili = 1880, Aciklama = 'Dostoyevski''nin son ve en büyük eseri. Bir baba katli etrafında şekillenen roman, inanç, şüphe, özgür irade ve ahlak kavramlarını üç erkek kardeş üzerinden muazzam bir derinlikle tartışır.' WHERE KitapAdi = 'Karamazov Kardeşler';
UPDATE Kitaplar SET Yayinevi = 'İş Bankası Kültür Yayınları', BasimYili = 1862, Aciklama = 'Ekmek çaldığı için kürek mahkumiyetine çarptırılan Jean Valjean''ın kefaret ve merhamet arayışını anlatan, Fransız Devrimi sonrası toplumsal adaletsizliğe tutulmuş devasa bir ayna.' WHERE KitapAdi = 'Sefiller';
UPDATE Kitaplar SET Yayinevi = 'İletişim Yayınları', BasimYili = 1869, Aciklama = 'Napolyon''un Rusya''yı işgali sırasında beş soylu ailenin yaşadıklarını merkeze alan, aşk, savaş, tarih ve insan doğası üzerine yazılmış destansı bir tarihsel roman.' WHERE KitapAdi = 'Savaş ve Barış';
UPDATE Kitaplar SET Yayinevi = 'İş Bankası Kültür Yayınları', BasimYili = 1877, Aciklama = 'Evli bir kadın olan Anna''nın, Kont Vronski ile yaşadığı yasak aşkın toplumsal kurallarla çarpışmasını ve trajik sonunu anlatan unutulmaz bir klasik.' WHERE KitapAdi = 'Anna Karenina';
UPDATE Kitaplar SET Yayinevi = 'Can Yayınları', BasimYili = 1813, Aciklama = 'Taşralı bir beyefendinin kızı olan Elizabeth Bennet ile varlıklı ve soylu Fitzwilliam Darcy arasındaki çatışmalı aşkı, dönemin İngiliz burjuvazisinin ince bir hicviyle anlatan eser.' WHERE KitapAdi = 'Gurur ve Önyargı';
UPDATE Kitaplar SET Yayinevi = 'İş Bankası Kültür Yayınları', BasimYili = 1864, Aciklama = 'Modern edebiyatın ilk varoluşçu anti-kahramanı olan isimsiz anlatıcının, topluma, bilime ve rasyonaliteye duyduğu öfkeyi kustuğu sarsıcı bir yeraltı itirafı.' WHERE KitapAdi = 'Yeraltından Notlar';
UPDATE Kitaplar SET Yayinevi = 'İş Bankası Kültür Yayınları', BasimYili = 1866, Aciklama = 'Yazarın kendi kumar bağımlılığından izler taşıyan roman, kurgusal bir Alman kasabasında rulet masaları etrafında dönen hastalıklı bir tutkuyu ve yıkımı anlatır.' WHERE KitapAdi = 'Kumarbaz';

UPDATE Kitaplar SET Yayinevi = 'Can Yayınları', BasimYili = 1949, Aciklama = 'Büyük Birader''in her şeyi izlediği, düşünmenin bile suç olduğu totaliter bir devlette geçen, gerçeğin ve tarihin nasıl manipüle edildiğini gösteren sarsıcı distopya.' WHERE KitapAdi = '1984';
UPDATE Kitaplar SET Yayinevi = 'Can Yayınları', BasimYili = 1945, Aciklama = 'İnsanların zorbalığına karşı ayaklanıp çiftliği ele geçiren hayvanların, zamanla kendi içlerinde yeni bir diktatörlük kurmalarını anlatan zekice bir siyasi hiciv.' WHERE KitapAdi = 'Hayvan Çiftliği';
UPDATE Kitaplar SET Yayinevi = 'Yapı Kredi Yayınları', BasimYili = 1943, Aciklama = 'İçine kapanık Raif Efendi''nin, Berlin''de bir sanat galerisinde tablosunu gördüğü Maria Puder''e duyduğu tutkulu aşkı ve sonrasında yaşadığı büyük sessizliği konu alır.' WHERE KitapAdi = 'Kürk Mantolu Madonna';
UPDATE Kitaplar SET Yayinevi = 'Yapı Kredi Yayınları', BasimYili = 1940, Aciklama = 'Ömer ve Macide''nin aşkı üzerinden, 1930''lar Türkiyesi''ndeki aydın kesimin yozlaşmasını, iradesizliğini ve içlerindeki "şeytan" ile olan çatışmalarını resmeder.' WHERE KitapAdi = 'İçimizdeki Şeytan';
UPDATE Kitaplar SET Yayinevi = 'Yapı Kredi Yayınları', BasimYili = 1937, Aciklama = 'Ailesi katledildikten sonra bir kaymakam tarafından evlat edinilen Yusuf''un, Anadolu kasabasının yozlaşmış eşrafına ve haksızlıklara karşı verdiği trajik mücadele.' WHERE KitapAdi = 'Kuyucaklı Yusuf';
UPDATE Kitaplar SET Yayinevi = 'İş Bankası Kültür Yayınları', BasimYili = 1943, Aciklama = 'Gestapo tarafından bir otel odasına hapsedilen ve zihnini korumak için satranç tahtasını zihninde canlandıran Dr. B''nin, bir yolcu gemisindeki dünya şampiyonuyla karşılaşması.' WHERE KitapAdi = 'Satranç';
UPDATE Kitaplar SET Yayinevi = 'İş Bankası Kültür Yayınları', BasimYili = 1922, Aciklama = 'Ünlü bir yazara gönderilen imzasız bir mektuptan okuduğumuz, yazarın hiç fark etmediği bir kadının çocukluğundan ölümüne kadar süren takıntılı ve karşılıksız aşkının melankolik itirafı.' WHERE KitapAdi = 'Bilinmeyen Bir Kadının Mektubu';
UPDATE Kitaplar SET Yayinevi = 'Can Yayınları', BasimYili = 1915, Aciklama = 'Kumaş pazarlamacısı Gregor Samsa''nın bir sabah yatağında dev bir böceğe dönüşmüş olarak uyanmasıyla başlayan, modern insanın sisteme yabancılaşmasının en somut tasviri.' WHERE KitapAdi = 'Dönüşüm';
UPDATE Kitaplar SET Yayinevi = 'Can Yayınları', BasimYili = 1925, Aciklama = 'Josef K.''nın bir sabah ansızın neyle suçlandığını bilmeden tutuklanması ve absürt, görünmez bir hukuk sistemine karşı verdiği çaresiz mücadeleyi anlatan başyapıt.' WHERE KitapAdi = 'Dava';
UPDATE Kitaplar SET Yayinevi = 'Dergah Yayınları', BasimYili = 1961, Aciklama = 'Hayri İrdal ve Halit Ayarcı üzerinden, Türk toplumunun Doğu-Batı arasındaki bocalayışını, eski ile yeni arasındaki çatışmayı absürt bir bürokrasi eleştirisiyle sunan eşsiz bir roman.' WHERE KitapAdi = 'Saatleri Ayarlama Enstitüsü';
UPDATE Kitaplar SET Yayinevi = 'Dergah Yayınları', BasimYili = 1949, Aciklama = 'Mümtaz ve Nuran''ın İstanbul fonunda yeşeren aşkı etrafında, Cumhuriyet aydınının gelenekle modernlik, geçmişle gelecek arasında yaşadığı derin huzursuzluğu şiirsel bir dille işler.' WHERE KitapAdi = 'Huzur';
UPDATE Kitaplar SET Yayinevi = 'İletişim Yayınları', BasimYili = 1972, Aciklama = 'Turgut Özben''in, intihar eden arkadaşı Selim Işık''ın geçmişinin izini sürerken, küçük burjuva ahlakına ve toplumsal kalıplara isyan eden "tutunamayanlar"ın dünyasına girmesini anlatır.' WHERE KitapAdi = 'Tutunamayanlar';
UPDATE Kitaplar SET Yayinevi = 'İletişim Yayınları', BasimYili = 1973, Aciklama = 'Hikmet Benol''un gecekondu mahallesinde kendi zihninde yarattığı oyunlar ve hayali karakterlerle gerçeği büküşünü, Türk aydınının trajikomik varoluş çırpınışını anlatan eser.' WHERE KitapAdi = 'Tehlikeli Oyunlar';
UPDATE Kitaplar SET Yayinevi = 'Can Yayınları', BasimYili = 1942, Aciklama = 'Annesinin ölümüne dahi tepkisiz kalan, toplumsal normlara ve ahlak kurallarına tamamen yabancılaşmış Meursault''nun, işlediği anlamsız cinayet sonrası absürt felsefesini yargıya sunuşu.' WHERE KitapAdi = 'Yabancı';
UPDATE Kitaplar SET Yayinevi = 'Can Yayınları', BasimYili = 1947, Aciklama = 'Cezayir''in Oran şehrinde veba salgınının patlak vermesiyle karantinaya alınan halkın, felaket karşısında gösterdiği dayanışmayı ve insanın ölüme karşı isyanını anlatan alegorik bir eser.' WHERE KitapAdi = 'Veba';
UPDATE Kitaplar SET Yayinevi = 'İthaki Yayınları', BasimYili = 1870, Aciklama = 'Deniz canavarı sanılan Nautilus denizaltısının esrarengiz Kaptan Nemo''su ve ona esir düşen Profesör Aronnax''ın okyanusların derinliklerinde yaşadığı nefes kesici bilimkurgu serüveni.' WHERE KitapAdi = 'Denizler Altında Yirmibin Fersah';
UPDATE Kitaplar SET Yayinevi = 'İthaki Yayınları', BasimYili = 1873, Aciklama = 'İngiliz beyefendisi Phileas Fogg''un, girdiği bir iddia üzerine uşağı Passepartout ile birlikte dünyanın etrafını 80 günde dönmek için vapurlar ve trenlerle girdiği zamana karşı yarış.' WHERE KitapAdi = 'Seksen Günde Devri Alem';
UPDATE Kitaplar SET Yayinevi = 'İş Bankası Kültür Yayınları', BasimYili = 1922, Aciklama = 'Tropik bir adada, zengin bir kadının yardım talebini reddeden bir doktorun, ardından hissettiği pişmanlık ve saplantıyla "amok" krizine girerek felakete sürüklenişinin hikayesi.' WHERE KitapAdi = 'Amok Koşucusu';

UPDATE Kitaplar SET Yayinevi = 'Altın Kitaplar', BasimYili = 1939, Aciklama = 'Birbirini tanımayan on kişinin ıssız bir adadaki malikaneye davet edilmeleri ve her birinin geçmişlerindeki sırlara göre sırayla öldürülmesini anlatan klasikleşmiş cinayet romanı.' WHERE KitapAdi = 'On Kişiydiler (On Küçük Zenci)';
UPDATE Kitaplar SET Yayinevi = 'Altın Kitaplar', BasimYili = 1934, Aciklama = 'Kar fırtınası yüzünden yolda kalan Doğu Ekspresi''nde işlenen esrarengiz cinayeti çözmek için Dedektif Hercule Poirot''nun yolcuları zekice sorguya çektiği efsanevi gizem.' WHERE KitapAdi = 'Doğu Ekspresinde Cinayet';
UPDATE Kitaplar SET Yayinevi = 'Altın Kitaplar', BasimYili = 1926, Aciklama = 'Zengin bir dulun intiharı ve hemen ardından Roger Ackroyd''un öldürülmesiyle başlayan, Hercule Poirot''nun polisiye tarihinin en şaşırtıcı ters köşelerinden birine imza attığı kitap.' WHERE KitapAdi = 'Roger Ackroyd Cinayeti';
UPDATE Kitaplar SET Yayinevi = 'Altın Kitaplar', BasimYili = 1937, Aciklama = 'Nil Nehri üzerinde lüks bir gemide balayına çıkan zengin bir mirasçının öldürülmesi ve Poirot''nun gemideki herkesin şüpheli olduğu bu karmaşık ağı çözme çabası.' WHERE KitapAdi = 'Nil''de Ölüm';
UPDATE Kitaplar SET Yayinevi = 'Ren Kitap', BasimYili = 1887, Aciklama = 'Dr. Watson''ın Sherlock Holmes ile tanıştığı, Baker Sokağı 221B''ye yerleştikleri ve Londra''da işlenen kanlı bir cinayeti tümdengelim yöntemiyle çözdükleri ilk büyük vaka.' WHERE KitapAdi = 'Sherlock Holmes - Kızıl Soruşturma';
UPDATE Kitaplar SET Yayinevi = 'Ren Kitap', BasimYili = 1890, Aciklama = 'Hindistan''dan İngiltere''ye uzanan gizemli bir hazinenin, zehirli okların ve eski ihanetlerin peşinden koşan Holmes ve Watson''ın en sürükleyici maceralarından biri.' WHERE KitapAdi = 'Sherlock Holmes - Dörtlerin İmzası';
UPDATE Kitaplar SET Yayinevi = 'Ren Kitap', BasimYili = 1902, Aciklama = 'Baskerville ailesinin nesillerdir peşinde olduğuna inanılan devasa ve şeytani bir köpeğin efsanesini araştırmak için sisli bataklıklara giden Holmes''un ürpertici soruşturması.' WHERE KitapAdi = 'Baskerville''lerin Köpeği';

UPDATE Kitaplar SET Yayinevi = 'Say Yayınları', BasimYili = 1899, Aciklama = 'Freud''un psikanaliz kuramının temel taşı olan bu eser, rüyaların tesadüfi olmadığını, bilinçdışı arzuların ve bastırılmış duyguların sansürlenmiş sembolik ifadeleri olduğunu savunur.' WHERE KitapAdi = 'Düşlerin Yorumu';
UPDATE Kitaplar SET Yayinevi = 'Metis Yayınları', BasimYili = 1930, Aciklama = 'İnsanın içgüdüsel arzuları (cinsellik ve saldırganlık) ile toplumun bu arzuları baskılayan kuralları arasındaki kaçınılmaz çatışmanın insanı nasıl nevrotik kıldığını anlatan başyapıt.' WHERE KitapAdi = 'Uygarlığın Huzursuzluğu';
UPDATE Kitaplar SET Yayinevi = 'Say Yayınları', BasimYili = 1901, Aciklama = 'Günlük hayatta yaptığımız dil sürçmelerinin, unutkanlıkların ve sakarlıkların aslında bilinçaltımızdaki gizli niyetlerin ve bastırılmış düşüncelerin dışa vurumu olduğunu inceleyen çalışma.' WHERE KitapAdi = 'Gündelik Hayatın Psikopatolojisi';
UPDATE Kitaplar SET Yayinevi = 'Pinhan Yayıncılık', BasimYili = 1928, Aciklama = 'Jung''un analitik psikolojisinin temellerini attığı, ego, gölge, anima/animus kavramlarını ve insan psişesinin yapısını mitoloji ve sembolizmle harmanlayarak anlattığı eseri.' WHERE KitapAdi = 'İnsan Ruhuna Yöneliş';
UPDATE Kitaplar SET Yayinevi = 'İthaki Yayınları', BasimYili = 1957, Aciklama = 'Modern kitle toplumlarında bireyin nasıl kaybolduğunu anlatan Jung, insanın kendini tanıması (bireyleşme) ve kendi "Gölge"siyle yüzleşmesi gerektiğini savunan uyarıcı bir manifestodur.' WHERE KitapAdi = 'Keşfedilmemiş Benlik';
UPDATE Kitaplar SET Yayinevi = 'Kaknüs Yayınları', BasimYili = 2009, Aciklama = 'Jung''un yıllarca herkesten sakladığı, kendi bilinçdışına yaptığı korkunç ve büyüleyici yolculukları, vizyonları ve arketiplerle karşılaşmalarını anlattığı, el yazması mistik günlüğü.' WHERE KitapAdi = 'Kırmızı Kitap';

UPDATE Kitaplar SET Yayinevi = 'İş Bankası Kültür Yayınları', BasimYili = 1883, Aciklama = 'Tanrının öldüğünü ilan eden Nietzsche''nin, "Üstinsan" kavramını ortaya attığı, geleneksel ahlakı yıkıp yerine insanın kendi değerlerini yaratmasını savunan şiirsel felsefe şaheseri.' WHERE KitapAdi = 'Böyle Söyledi Zerdüşt';
UPDATE Kitaplar SET Yayinevi = 'İş Bankası Kültür Yayınları', BasimYili = 1886, Aciklama = 'Mutlak doğruları, evrensel iyiyi ve kötüyü reddeden Nietzsche''nin, ahlakın aslında bir "güç istenci" yansıması olduğunu savunduğu sarsıcı ve provokatif denemeleri.' WHERE KitapAdi = 'İyinin ve Kötünün Ötesinde';
UPDATE Kitaplar SET Yayinevi = 'İş Bankası Kültür Yayınları', BasimYili = 1889, Aciklama = 'Sokrates''ten bu yana Batı felsefesinin taptığı "putları" (eski değerleri ve dogmaları) felsefi bir çekiçle yıktığını iddia eden, yazarın felsefesinin en yoğun özetlerinden biri.' WHERE KitapAdi = 'Putların Alacakaranlığı';
UPDATE Kitaplar SET Yayinevi = 'İş Bankası Kültür Yayınları', BasimYili = 180, Aciklama = 'Roma İmparatoru Marcus Aurelius''un seferler sırasında çadırında kendi kendine yazdığı, Stoacı felsefenin erdem, ölüm, doğaya uyum ve iç huzur üzerine en pratik rehberi.' WHERE KitapAdi = 'Kendime Düşünceler';
UPDATE Kitaplar SET Yayinevi = 'Can Yayınları', BasimYili = 1942, Aciklama = 'İnsanın anlam arayışının, anlamsız bir evrenle çarpışmasından doğan "Absürt" felsefesini, kayayı sonsuza dek dağa çıkarmaya mahkum edilen Sisifos efsanesi üzerinden inceler.' WHERE KitapAdi = 'Sisifos Söyleni';
UPDATE Kitaplar SET Yayinevi = 'Can Yayınları', BasimYili = 1951, Aciklama = 'İnsanın evrendeki anlamsızlığa karşı koyuşunun tek yolunun "isyan" olduğunu, ancak bu isyanın bir cinayete veya diktatörlüğe dönüşmemesi gerektiğini tartışan metafizik analiz.' WHERE KitapAdi = 'Başkaldıran İnsan';

UPDATE Kitaplar SET Yayinevi = 'Kolektif Kitap', BasimYili = 2011, Aciklama = 'Önemsiz bir maymun türü olan Homo Sapiens''in bilişsel, tarım ve bilim devrimleriyle gezegenin hakimi konumuna nasıl yükseldiğini anlatan, ezber bozan bir insanlık tarihi.' WHERE KitapAdi = 'Sapiens: Hayvanlardan Tanrılara';
UPDATE Kitaplar SET Yayinevi = 'Kolektif Kitap', BasimYili = 2015, Aciklama = 'Açlık, savaş ve hastalıkları yenen insanlığın, gelecekte ölümsüzlük, mutluluk ve tanrısallık peşinde koşarken yapay zeka ve biyoteknoloji ile kendi sonunu nasıl hazırlayabileceğini tartışır.' WHERE KitapAdi = 'Homo Deus: Yarının Kısa Tarihi';
UPDATE Kitaplar SET Yayinevi = 'Kolektif Kitap', BasimYili = 2018, Aciklama = 'Sahte haberler, teknolojik işsizlik, göçmen krizleri ve ekolojik çöküş gibi günümüzün en yakıcı küresel sorunlarına tarihsel ve felsefi bir mercekten bakan derin bir analiz.' WHERE KitapAdi = '21. Yüzyıl İçin 21 Ders';
UPDATE Kitaplar SET Yayinevi = 'Kronik Kitap', BasimYili = 2019, Aciklama = 'İlber Ortaylı''nın kendi deneyimlerinden yola çıkarak, seyahat etmek, dil öğrenmek, meslek seçimi ve müzik zevki gibi konularda gençlere ufuk açıcı bir yaşam rehberi sunduğu söyleşi kitabı.' WHERE KitapAdi = 'Bir Ömür Nasıl Yaşanır?';
UPDATE Kitaplar SET Yayinevi = 'Kronik Kitap', BasimYili = 2018, Aciklama = 'İlber Ortaylı''nın kaleminden, Mustafa Kemal Atatürk''ün askeri dehasını, vizyonunu, Cumhuriyet''i kurarken verdiği siyasi mücadeleleri tarihi belgeler ışığında anlatan muazzam biyografi.' WHERE KitapAdi = 'Gazi Mustafa Kemal Atatürk';
GO