using Microsoft.EntityFrameworkCore;
using System.IO;

namespace NovaKitap.Models
{
    public static class ModelBuilderExtensions
    {
        public static void Seed(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Kategoriler>().HasData(
                new Kategoriler { KategoriId = 1, KategoriAdi = "Klasik", IkonSifi = "✧" },
                new Kategoriler { KategoriId = 2, KategoriAdi = "Edebiyat", IkonSifi = "✧" },
                new Kategoriler { KategoriId = 3, KategoriAdi = "Psikoloji", IkonSifi = "✧" },
                new Kategoriler { KategoriId = 4, KategoriAdi = "Tarih", IkonSifi = "✧" },
                new Kategoriler { KategoriId = 5, KategoriAdi = "Felsefe", IkonSifi = "✧" },
                new Kategoriler { KategoriId = 6, KategoriAdi = "Polisiye", IkonSifi = "✧" },
                new Kategoriler { KategoriId = 7, KategoriAdi = "Roman", IkonSifi = "✧" }
            );

            modelBuilder.Entity<Yazarlar>().HasData(
                new Yazarlar { YazarId = 1, AdSoyad = "Fyodor Dostoyevski", Biyografi = "Rus edebiyatının en büyük yazarlarından." },
                new Yazarlar { YazarId = 2, AdSoyad = "George Orwell", Biyografi = "Distopik eserleriyle tanınan İngiliz yazar." },
                new Yazarlar { YazarId = 3, AdSoyad = "Sabahattin Ali", Biyografi = "Türk edebiyatının usta kalemlerinden." },
                new Yazarlar { YazarId = 4, AdSoyad = "Stefan Zweig", Biyografi = "Avusturyalı romancı ve biyografi yazarı." },
                new Yazarlar { YazarId = 5, AdSoyad = "Franz Kafka", Biyografi = "Modern Alman edebiyatının öncülerinden." },
                new Yazarlar { YazarId = 6, AdSoyad = "Agatha Christie", Biyografi = "Polisiye edebiyatın kraliçesi." },
                new Yazarlar { YazarId = 7, AdSoyad = "Victor Hugo", Biyografi = "Fransız edebiyatının en büyük romantik yazarı." },
                new Yazarlar { YazarId = 8, AdSoyad = "Sigmund Freud", Biyografi = "Psikanalizin kurucusu." },
                new Yazarlar { YazarId = 9, AdSoyad = "Friedrich Nietzsche", Biyografi = "Alman filozof ve kültür eleştirmeni." },
                new Yazarlar { YazarId = 10, AdSoyad = "İlber Ortaylı", Biyografi = "Türk tarihçi ve akademisyen." },
                new Yazarlar { YazarId = 11, AdSoyad = "Ahmet Hamdi Tanpınar", Biyografi = "Türk romanının ve şiirinin önemli ismi." },
                new Yazarlar { YazarId = 12, AdSoyad = "Oğuz Atay", Biyografi = "Postmodern Türk edebiyatının kurucularından." },
                new Yazarlar { YazarId = 13, AdSoyad = "Albert Camus", Biyografi = "Varoluşçuluk akımının öncülerinden." },
                new Yazarlar { YazarId = 14, AdSoyad = "Lev Tolstoy", Biyografi = "Gerçekçi Rus edebiyatının dev ismi." },
                new Yazarlar { YazarId = 15, AdSoyad = "Arthur Conan Doyle", Biyografi = "Sherlock Holmes karakterinin yaratıcısı." },
                new Yazarlar { YazarId = 16, AdSoyad = "Yuval Noah Harari", Biyografi = "İsrailli tarihçi ve yazar." },
                new Yazarlar { YazarId = 17, AdSoyad = "Marcus Aurelius", Biyografi = "Roma imparatoru ve Stoacı filozof." },
                new Yazarlar { YazarId = 18, AdSoyad = "Jules Verne", Biyografi = "Bilimkurgu edebiyatının babası." },
                new Yazarlar { YazarId = 19, AdSoyad = "Jane Austen", Biyografi = "İngiliz edebiyatının romantik dönem yazarı." },
                new Yazarlar { YazarId = 20, AdSoyad = "Carl Gustav Jung", Biyografi = "Analitik psikolojinin kurucusu." }
            );

            modelBuilder.Entity<Kitaplar>().HasData(                new Kitaplar { KitapId = 1, KitapAdi = "Suç ve Ceza", Aciklama = "Fakir bir öğrenci olan Raskolnikov'un işlediği cinayet sonrası yaşadığı derin vicdan azabı ve psikolojik buhranı anlatan, insan ruhunun karanlık dehlizlerine inen eşsiz bir başyapıt.", SayfaSayisi = 687, Fiyat = 145.50m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Suc+ve+Ceza", YeniCikanMi = false, CokSatanMi = true, YazarId = 1, KategoriId = 1, Yayinevi = "İş Bankası Kültür Yayınları", BasimYili = 1866, StokAdedi = 50 },
                new Kitaplar { KitapId = 2, KitapAdi = "Karamazov Kardeşler", Aciklama = "Dostoyevski'nin son ve en büyük eseri. Bir baba katli etrafında şekillenen roman, inanç, şüphe, özgür irade ve ahlak kavramlarını üç erkek kardeş üzerinden muazzam bir derinlikle tartışır.", SayfaSayisi = 840, Fiyat = 185.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Karamazov", YeniCikanMi = false, CokSatanMi = false, YazarId = 1, KategoriId = 1, Yayinevi = "İş Bankası Kültür Yayınları", BasimYili = 1880, StokAdedi = 50 },
                new Kitaplar { KitapId = 3, KitapAdi = "Sefiller", Aciklama = "Ekmek çaldığı için kürek mahkumiyetine çarptırılan Jean Valjean'ın kefaret ve merhamet arayışını anlatan, Fransız Devrimi sonrası toplumsal adaletsizliğe tutulmuş devasa bir ayna.", SayfaSayisi = 1200, Fiyat = 250.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Sefiller", YeniCikanMi = false, CokSatanMi = true, YazarId = 7, KategoriId = 1, Yayinevi = "İş Bankası Kültür Yayınları", BasimYili = 1862, StokAdedi = 50 },
                new Kitaplar { KitapId = 4, KitapAdi = "Savaş ve Barış", Aciklama = "Napolyon'un Rusya'yı işgali sırasında beş soylu ailenin yaşadıklarını merkeze alan, aşk, savaş, tarih ve insan doğası üzerine yazılmış destansı bir tarihsel roman.", SayfaSayisi = 1225, Fiyat = 275.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Savas+ve+Baris", YeniCikanMi = false, CokSatanMi = false, YazarId = 14, KategoriId = 1, Yayinevi = "İletişim Yayınları", BasimYili = 1869, StokAdedi = 50 },
                new Kitaplar { KitapId = 5, KitapAdi = "Anna Karenina", Aciklama = "Evli bir kadın olan Anna'nın, Kont Vronski ile yaşadığı yasak aşkın toplumsal kurallarla çarpışmasını ve trajik sonunu anlatan unutulmaz bir klasik.", SayfaSayisi = 864, Fiyat = 190.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Anna+Karenina", YeniCikanMi = false, CokSatanMi = false, YazarId = 14, KategoriId = 1, Yayinevi = "İş Bankası Kültür Yayınları", BasimYili = 1877, StokAdedi = 50 },
                new Kitaplar { KitapId = 6, KitapAdi = "Gurur ve Önyargı", Aciklama = "Taşralı bir beyefendinin kızı olan Elizabeth Bennet ile varlıklı ve soylu Fitzwilliam Darcy arasındaki çatışmalı aşkı, dönemin İngiliz burjuvazisinin ince bir hicviyle anlatan eser.", SayfaSayisi = 432, Fiyat = 95.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Gurur+ve+Onyargi", YeniCikanMi = false, CokSatanMi = true, YazarId = 19, KategoriId = 1, Yayinevi = "Can Yayınları", BasimYili = 1813, StokAdedi = 50 },
                new Kitaplar { KitapId = 7, KitapAdi = "Yeraltından Notlar", Aciklama = "Modern edebiyatın ilk varoluşçu anti-kahramanı olan isimsiz anlatıcının, topluma, bilime ve rasyonaliteye duyduğu öfkeyi kustuğu sarsıcı bir yeraltı itirafı.", SayfaSayisi = 150, Fiyat = 65.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Yeraltindan", YeniCikanMi = true, CokSatanMi = false, YazarId = 1, KategoriId = 1, Yayinevi = "İş Bankası Kültür Yayınları", BasimYili = 1864, StokAdedi = 50 },
                new Kitaplar { KitapId = 8, KitapAdi = "Kumarbaz", Aciklama = "Yazarın kendi kumar bağımlılığından izler taşıyan roman, kurgusal bir Alman kasabasında rulet masaları etrafında dönen hastalıklı bir tutkuyu ve yıkımı anlatır.", SayfaSayisi = 190, Fiyat = 75.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Kumarbaz", YeniCikanMi = false, CokSatanMi = false, YazarId = 1, KategoriId = 1, Yayinevi = "İş Bankası Kültür Yayınları", BasimYili = 1866, StokAdedi = 50 },
                new Kitaplar { KitapId = 9, KitapAdi = "1984", Aciklama = "Büyük Birader'in her şeyi izlediği, düşünmenin bile suç olduğu totaliter bir devlette geçen, gerçeğin ve tarihin nasıl manipüle edildiğini gösteren sarsıcı distopya.", SayfaSayisi = 352, Fiyat = 110.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=1984", YeniCikanMi = false, CokSatanMi = true, YazarId = 2, KategoriId = 7, Yayinevi = "Can Yayınları", BasimYili = 1949, StokAdedi = 50 },
                new Kitaplar { KitapId = 10, KitapAdi = "Hayvan Çiftliği", Aciklama = "İnsanların zorbalığına karşı ayaklanıp çiftliği ele geçiren hayvanların, zamanla kendi içlerinde yeni bir diktatörlük kurmalarını anlatan zekice bir siyasi hiciv.", SayfaSayisi = 152, Fiyat = 85.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Hayvan+Ciftligi", YeniCikanMi = true, CokSatanMi = true, YazarId = 2, KategoriId = 7, Yayinevi = "Can Yayınları", BasimYili = 1945, StokAdedi = 50 },
                new Kitaplar { KitapId = 11, KitapAdi = "Kürk Mantolu Madonna", Aciklama = "İçine kapanık Raif Efendi'nin, Berlin'de bir sanat galerisinde tablosunu gördüğü Maria Puder'e duyduğu tutkulu aşkı ve sonrasında yaşadığı büyük sessizliği konu alır.", SayfaSayisi = 160, Fiyat = 70.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Kurk+Mantolu", YeniCikanMi = false, CokSatanMi = true, YazarId = 3, KategoriId = 7, Yayinevi = "Yapı Kredi Yayınları", BasimYili = 1943, StokAdedi = 50 },
                new Kitaplar { KitapId = 12, KitapAdi = "İçimizdeki Şeytan", Aciklama = "Ömer ve Macide'nin aşkı üzerinden, 1930'lar Türkiyesi'ndeki aydın kesimin yozlaşmasını, iradesizliğini ve içlerindeki \"şeytan\" ile olan çatışmalarını resmeder.", SayfaSayisi = 260, Fiyat = 90.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Icimizdeki+Seytan", YeniCikanMi = false, CokSatanMi = false, YazarId = 3, KategoriId = 7, Yayinevi = "Yapı Kredi Yayınları", BasimYili = 1940, StokAdedi = 50 },
                new Kitaplar { KitapId = 13, KitapAdi = "Kuyucaklı Yusuf", Aciklama = "Ailesi katledildikten sonra bir kaymakam tarafından evlat edinilen Yusuf'un, Anadolu kasabasının yozlaşmış eşrafına ve haksızlıklara karşı verdiği trajik mücadele.", SayfaSayisi = 220, Fiyat = 85.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Kuyucakli+Yusuf", YeniCikanMi = false, CokSatanMi = false, YazarId = 3, KategoriId = 7, Yayinevi = "Yapı Kredi Yayınları", BasimYili = 1937, StokAdedi = 50 },
                new Kitaplar { KitapId = 14, KitapAdi = "Satranç", Aciklama = "Gestapo tarafından bir otel odasına hapsedilen ve zihnini korumak için satranç tahtasını zihninde canlandıran Dr. B'nin, bir yolcu gemisindeki dünya şampiyonuyla karşılaşması.", SayfaSayisi = 85, Fiyat = 45.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Satranc", YeniCikanMi = true, CokSatanMi = true, YazarId = 4, KategoriId = 7, Yayinevi = "İş Bankası Kültür Yayınları", BasimYili = 1943, StokAdedi = 50 },
                new Kitaplar { KitapId = 15, KitapAdi = "Bilinmeyen Bir Kadının Mektubu", Aciklama = "Ünlü bir yazara gönderilen imzasız bir mektuptan okuduğumuz, yazarın hiç fark etmediği bir kadının çocukluğundan ölümüne kadar süren takıntılı ve karşılıksız aşkının melankolik itirafı.", SayfaSayisi = 65, Fiyat = 35.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Bilinmeyen+Kadin", YeniCikanMi = false, CokSatanMi = false, YazarId = 4, KategoriId = 7, Yayinevi = "İş Bankası Kültür Yayınları", BasimYili = 1922, StokAdedi = 50 },
                new Kitaplar { KitapId = 16, KitapAdi = "Dönüşüm", Aciklama = "Kumaş pazarlamacısı Gregor Samsa'nın bir sabah yatağında dev bir böceğe dönüşmüş olarak uyanmasıyla başlayan, modern insanın sisteme yabancılaşmasının en somut tasviri.", SayfaSayisi = 104, Fiyat = 55.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Donusum", YeniCikanMi = false, CokSatanMi = true, YazarId = 5, KategoriId = 2, Yayinevi = "Can Yayınları", BasimYili = 1915, StokAdedi = 50 },
                new Kitaplar { KitapId = 17, KitapAdi = "Dava", Aciklama = "Josef K.'nın bir sabah ansızın neyle suçlandığını bilmeden tutuklanması ve absürt, görünmez bir hukuk sistemine karşı verdiği çaresiz mücadeleyi anlatan başyapıt.", SayfaSayisi = 270, Fiyat = 95.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Dava", YeniCikanMi = false, CokSatanMi = false, YazarId = 5, KategoriId = 2, Yayinevi = "Can Yayınları", BasimYili = 1925, StokAdedi = 50 },
                new Kitaplar { KitapId = 18, KitapAdi = "Saatleri Ayarlama Enstitüsü", Aciklama = "Hayri İrdal ve Halit Ayarcı üzerinden, Türk toplumunun Doğu-Batı arasındaki bocalayışını, eski ile yeni arasındaki çatışmayı absürt bir bürokrasi eleştirisiyle sunan eşsiz bir roman.", SayfaSayisi = 382, Fiyat = 130.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Saatleri+Ayarlama", YeniCikanMi = true, CokSatanMi = true, YazarId = 11, KategoriId = 7, Yayinevi = "Dergah Yayınları", BasimYili = 1961, StokAdedi = 50 },
                new Kitaplar { KitapId = 19, KitapAdi = "Huzur", Aciklama = "Mümtaz ve Nuran'ın İstanbul fonunda yeşeren aşkı etrafında, Cumhuriyet aydınının gelenekle modernlik, geçmişle gelecek arasında yaşadığı derin huzursuzluğu şiirsel bir dille işler.", SayfaSayisi = 390, Fiyat = 135.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Huzur", YeniCikanMi = false, CokSatanMi = false, YazarId = 11, KategoriId = 2, Yayinevi = "Dergah Yayınları", BasimYili = 1949, StokAdedi = 50 },
                new Kitaplar { KitapId = 20, KitapAdi = "Tutunamayanlar", Aciklama = "Turgut Özben'in, intihar eden arkadaşı Selim Işık'ın geçmişinin izini sürerken, küçük burjuva ahlakına ve toplumsal kalıplara isyan eden \"tutunamayanlar\"ın dünyasına girmesini anlatır.", SayfaSayisi = 724, Fiyat = 210.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Tutunamayanlar", YeniCikanMi = false, CokSatanMi = true, YazarId = 12, KategoriId = 7, Yayinevi = "İletişim Yayınları", BasimYili = 1972, StokAdedi = 50 },
                new Kitaplar { KitapId = 21, KitapAdi = "Tehlikeli Oyunlar", Aciklama = "Hikmet Benol'un gecekondu mahallesinde kendi zihninde yarattığı oyunlar ve hayali karakterlerle gerçeği büküşünü, Türk aydınının trajikomik varoluş çırpınışını anlatan eser.", SayfaSayisi = 480, Fiyat = 150.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Tehlikeli+Oyunlar", YeniCikanMi = false, CokSatanMi = false, YazarId = 12, KategoriId = 7, Yayinevi = "İletişim Yayınları", BasimYili = 1973, StokAdedi = 50 },
                new Kitaplar { KitapId = 22, KitapAdi = "Yabancı", Aciklama = "Annesinin ölümüne dahi tepkisiz kalan, toplumsal normlara ve ahlak kurallarına tamamen yabancılaşmış Meursault'nun, işlediği anlamsız cinayet sonrası absürt felsefesini yargıya sunuşu.", SayfaSayisi = 112, Fiyat = 60.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Yabanci", YeniCikanMi = true, CokSatanMi = true, YazarId = 13, KategoriId = 2, Yayinevi = "Can Yayınları", BasimYili = 1942, StokAdedi = 50 },
                new Kitaplar { KitapId = 23, KitapAdi = "Veba", Aciklama = "Cezayir'in Oran şehrinde veba salgınının patlak vermesiyle karantinaya alınan halkın, felaket karşısında gösterdiği dayanışmayı ve insanın ölüme karşı isyanını anlatan alegorik bir eser.", SayfaSayisi = 300, Fiyat = 115.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Veba", YeniCikanMi = false, CokSatanMi = false, YazarId = 13, KategoriId = 2, Yayinevi = "Can Yayınları", BasimYili = 1947, StokAdedi = 50 },
                new Kitaplar { KitapId = 24, KitapAdi = "Denizler Altında Yirmibin Fersah", Aciklama = "Deniz canavarı sanılan Nautilus denizaltısının esrarengiz Kaptan Nemo'su ve ona esir düşen Profesör Aronnax'ın okyanusların derinliklerinde yaşadığı nefes kesici bilimkurgu serüveni.", SayfaSayisi = 450, Fiyat = 125.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Denizler+Altinda", YeniCikanMi = false, CokSatanMi = false, YazarId = 18, KategoriId = 7, Yayinevi = "İthaki Yayınları", BasimYili = 1870, StokAdedi = 50 },
                new Kitaplar { KitapId = 25, KitapAdi = "Seksen Günde Devri Alem", Aciklama = "İngiliz beyefendisi Phileas Fogg'un, girdiği bir iddia üzerine uşağı Passepartout ile birlikte dünyanın etrafını 80 günde dönmek için vapurlar ve trenlerle girdiği zamana karşı yarış.", SayfaSayisi = 320, Fiyat = 110.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Seksen+Gunde", YeniCikanMi = true, CokSatanMi = false, YazarId = 18, KategoriId = 7, Yayinevi = "İthaki Yayınları", BasimYili = 1873, StokAdedi = 50 },
                new Kitaplar { KitapId = 26, KitapAdi = "Amok Koşucusu", Aciklama = "Tropik bir adada, zengin bir kadının yardım talebini reddeden bir doktorun, ardından hissettiği pişmanlık ve saplantıyla \"amok\" krizine girerek felakete sürüklenişinin hikayesi.", SayfaSayisi = 70, Fiyat = 40.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Amok+Kosucusu", YeniCikanMi = false, CokSatanMi = false, YazarId = 4, KategoriId = 2, Yayinevi = "İş Bankası Kültür Yayınları", BasimYili = 1922, StokAdedi = 50 },
                new Kitaplar { KitapId = 27, KitapAdi = "On Kişiydiler (On Küçük Zenci)", Aciklama = "Birbirini tanımayan on kişinin ıssız bir adadaki malikaneye davet edilmeleri ve her birinin geçmişlerindeki sırlara göre sırayla öldürülmesini anlatan klasikleşmiş cinayet romanı.", SayfaSayisi = 224, Fiyat = 105.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=On+Kisiydiler", YeniCikanMi = false, CokSatanMi = true, YazarId = 6, KategoriId = 6, Yayinevi = "Altın Kitaplar", BasimYili = 1939, StokAdedi = 50 },
                new Kitaplar { KitapId = 28, KitapAdi = "Doğu Ekspresinde Cinayet", Aciklama = "Kar fırtınası yüzünden yolda kalan Doğu Ekspresi'nde işlenen esrarengiz cinayeti çözmek için Dedektif Hercule Poirot'nun yolcuları zekice sorguya çektiği efsanevi gizem.", SayfaSayisi = 256, Fiyat = 115.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Dogu+Ekspresinde", YeniCikanMi = true, CokSatanMi = true, YazarId = 6, KategoriId = 6, Yayinevi = "Altın Kitaplar", BasimYili = 1934, StokAdedi = 50 },
                new Kitaplar { KitapId = 29, KitapAdi = "Roger Ackroyd Cinayeti", Aciklama = "Zengin bir dulun intiharı ve hemen ardından Roger Ackroyd'un öldürülmesiyle başlayan, Hercule Poirot'nun polisiye tarihinin en şaşırtıcı ters köşelerinden birine imza attığı kitap.", SayfaSayisi = 280, Fiyat = 120.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Roger+Ackroyd", YeniCikanMi = false, CokSatanMi = false, YazarId = 6, KategoriId = 6, Yayinevi = "Altın Kitaplar", BasimYili = 1926, StokAdedi = 50 },
                new Kitaplar { KitapId = 30, KitapAdi = "Nil'de Ölüm", Aciklama = "Mısırda bir gemi yolculuğunda trajedi.", SayfaSayisi = 310, Fiyat = 130.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Nilde+Olum", YeniCikanMi = false, CokSatanMi = false, YazarId = 6, KategoriId = 6, Yayinevi = "Bilinmiyor", BasimYili = 2020, StokAdedi = 50 },
                new Kitaplar { KitapId = 31, KitapAdi = "Sherlock Holmes - Kızıl Soruşturma", Aciklama = "Dr. Watson'ın Sherlock Holmes ile tanıştığı, Baker Sokağı 221B'ye yerleştikleri ve Londra'da işlenen kanlı bir cinayeti tümdengelim yöntemiyle çözdükleri ilk büyük vaka.", SayfaSayisi = 160, Fiyat = 75.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Kizil+Sorusturma", YeniCikanMi = true, CokSatanMi = true, YazarId = 15, KategoriId = 6, Yayinevi = "Ren Kitap", BasimYili = 1887, StokAdedi = 50 },
                new Kitaplar { KitapId = 32, KitapAdi = "Sherlock Holmes - Dörtlerin İmzası", Aciklama = "Hindistan'dan İngiltere'ye uzanan gizemli bir hazinenin, zehirli okların ve eski ihanetlerin peşinden koşan Holmes ve Watson'ın en sürükleyici maceralarından biri.", SayfaSayisi = 180, Fiyat = 80.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Dortlerin+Imzasi", YeniCikanMi = false, CokSatanMi = false, YazarId = 15, KategoriId = 6, Yayinevi = "Ren Kitap", BasimYili = 1890, StokAdedi = 50 },
                new Kitaplar { KitapId = 33, KitapAdi = "Baskerville'lerin Köpeği", Aciklama = "Lanetli bir ailenin sırrı.", SayfaSayisi = 240, Fiyat = 100.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Baskervillelerin", YeniCikanMi = false, CokSatanMi = true, YazarId = 15, KategoriId = 6, Yayinevi = "Bilinmiyor", BasimYili = 2020, StokAdedi = 50 },
                new Kitaplar { KitapId = 34, KitapAdi = "Düşlerin Yorumu", Aciklama = "Freud'un psikanaliz kuramının temel taşı olan bu eser, rüyaların tesadüfi olmadığını, bilinçdışı arzuların ve bastırılmış duyguların sansürlenmiş sembolik ifadeleri olduğunu savunur.", SayfaSayisi = 550, Fiyat = 180.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Duslerin+Yorumu", YeniCikanMi = false, CokSatanMi = true, YazarId = 8, KategoriId = 3, Yayinevi = "Say Yayınları", BasimYili = 1899, StokAdedi = 50 },
                new Kitaplar { KitapId = 35, KitapAdi = "Uygarlığın Huzursuzluğu", Aciklama = "İnsanın içgüdüsel arzuları (cinsellik ve saldırganlık) ile toplumun bu arzuları baskılayan kuralları arasındaki kaçınılmaz çatışmanın insanı nasıl nevrotik kıldığını anlatan başyapıt.", SayfaSayisi = 120, Fiyat = 65.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Uygarligin", YeniCikanMi = true, CokSatanMi = false, YazarId = 8, KategoriId = 3, Yayinevi = "Metis Yayınları", BasimYili = 1930, StokAdedi = 50 },
                new Kitaplar { KitapId = 36, KitapAdi = "Gündelik Hayatın Psikopatolojisi", Aciklama = "Günlük hayatta yaptığımız dil sürçmelerinin, unutkanlıkların ve sakarlıkların aslında bilinçaltımızdaki gizli niyetlerin ve bastırılmış düşüncelerin dışa vurumu olduğunu inceleyen çalışma.", SayfaSayisi = 320, Fiyat = 135.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Psikopatoloji", YeniCikanMi = false, CokSatanMi = false, YazarId = 8, KategoriId = 3, Yayinevi = "Say Yayınları", BasimYili = 1901, StokAdedi = 50 },
                new Kitaplar { KitapId = 37, KitapAdi = "İnsan Ruhuna Yöneliş", Aciklama = "Jung'un analitik psikolojisinin temellerini attığı, ego, gölge, anima/animus kavramlarını ve insan psişesinin yapısını mitoloji ve sembolizmle harmanlayarak anlattığı eseri.", SayfaSayisi = 280, Fiyat = 125.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Insan+Ruhuna", YeniCikanMi = false, CokSatanMi = false, YazarId = 20, KategoriId = 3, Yayinevi = "Pinhan Yayıncılık", BasimYili = 1928, StokAdedi = 50 },
                new Kitaplar { KitapId = 38, KitapAdi = "Keşfedilmemiş Benlik", Aciklama = "Modern kitle toplumlarında bireyin nasıl kaybolduğunu anlatan Jung, insanın kendini tanıması (bireyleşme) ve kendi \"Gölge\"siyle yüzleşmesi gerektiğini savunan uyarıcı bir manifestodur.", SayfaSayisi = 140, Fiyat = 75.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Kesfedilmemis+Benlik", YeniCikanMi = true, CokSatanMi = true, YazarId = 20, KategoriId = 3, Yayinevi = "İthaki Yayınları", BasimYili = 1957, StokAdedi = 50 },
                new Kitaplar { KitapId = 39, KitapAdi = "Kırmızı Kitap", Aciklama = "Jung'un yıllarca herkesten sakladığı, kendi bilinçdışına yaptığı korkunç ve büyüleyici yolculukları, vizyonları ve arketiplerle karşılaşmalarını anlattığı, el yazması mistik günlüğü.", SayfaSayisi = 400, Fiyat = 250.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Kirmizi+Kitap", YeniCikanMi = false, CokSatanMi = false, YazarId = 20, KategoriId = 3, Yayinevi = "Kaknüs Yayınları", BasimYili = 2009, StokAdedi = 50 },
                new Kitaplar { KitapId = 40, KitapAdi = "Böyle Söyledi Zerdüşt", Aciklama = "Tanrının öldüğünü ilan eden Nietzsche'nin, \"Üstinsan\" kavramını ortaya attığı, geleneksel ahlakı yıkıp yerine insanın kendi değerlerini yaratmasını savunan şiirsel felsefe şaheseri.", SayfaSayisi = 350, Fiyat = 140.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Zerdust", YeniCikanMi = false, CokSatanMi = true, YazarId = 9, KategoriId = 5, Yayinevi = "İş Bankası Kültür Yayınları", BasimYili = 1883, StokAdedi = 50 },
                new Kitaplar { KitapId = 41, KitapAdi = "İyinin ve Kötünün Ötesinde", Aciklama = "Mutlak doğruları, evrensel iyiyi ve kötüyü reddeden Nietzsche'nin, ahlakın aslında bir \"güç istenci\" yansıması olduğunu savunduğu sarsıcı ve provokatif denemeleri.", SayfaSayisi = 240, Fiyat = 110.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Iyinin+ve+Kotunun", YeniCikanMi = true, CokSatanMi = false, YazarId = 9, KategoriId = 5, Yayinevi = "İş Bankası Kültür Yayınları", BasimYili = 1886, StokAdedi = 50 },
                new Kitaplar { KitapId = 42, KitapAdi = "Putların Alacakaranlığı", Aciklama = "Sokrates'ten bu yana Batı felsefesinin taptığı \"putları\" (eski değerleri ve dogmaları) felsefi bir çekiçle yıktığını iddia eden, yazarın felsefesinin en yoğun özetlerinden biri.", SayfaSayisi = 130, Fiyat = 70.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Putlarin", YeniCikanMi = false, CokSatanMi = false, YazarId = 9, KategoriId = 5, Yayinevi = "İş Bankası Kültür Yayınları", BasimYili = 1889, StokAdedi = 50 },
                new Kitaplar { KitapId = 43, KitapAdi = "Kendime Düşünceler", Aciklama = "Roma İmparatoru Marcus Aurelius'un seferler sırasında çadırında kendi kendine yazdığı, Stoacı felsefenin erdem, ölüm, doğaya uyum ve iç huzur üzerine en pratik rehberi.", SayfaSayisi = 160, Fiyat = 80.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Kendime+Dusunceler", YeniCikanMi = true, CokSatanMi = true, YazarId = 17, KategoriId = 5, Yayinevi = "İş Bankası Kültür Yayınları", BasimYili = 180, StokAdedi = 50 },
                new Kitaplar { KitapId = 44, KitapAdi = "Sisifos Söyleni", Aciklama = "İnsanın anlam arayışının, anlamsız bir evrenle çarpışmasından doğan \"Absürt\" felsefesini, kayayı sonsuza dek dağa çıkarmaya mahkum edilen Sisifos efsanesi üzerinden inceler.", SayfaSayisi = 150, Fiyat = 75.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Sisifos+Soyleni", YeniCikanMi = false, CokSatanMi = true, YazarId = 13, KategoriId = 5, Yayinevi = "Can Yayınları", BasimYili = 1942, StokAdedi = 50 },
                new Kitaplar { KitapId = 45, KitapAdi = "Başkaldıran İnsan", Aciklama = "İnsanın evrendeki anlamsızlığa karşı koyuşunun tek yolunun \"isyan\" olduğunu, ancak bu isyanın bir cinayete veya diktatörlüğe dönüşmemesi gerektiğini tartışan metafizik analiz.", SayfaSayisi = 380, Fiyat = 145.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Baskaldiran", YeniCikanMi = false, CokSatanMi = false, YazarId = 13, KategoriId = 5, Yayinevi = "Can Yayınları", BasimYili = 1951, StokAdedi = 50 },
                new Kitaplar { KitapId = 46, KitapAdi = "Sapiens: Hayvanlardan Tanrılara", Aciklama = "Önemsiz bir maymun türü olan Homo Sapiens'in bilişsel, tarım ve bilim devrimleriyle gezegenin hakimi konumuna nasıl yükseldiğini anlatan, ezber bozan bir insanlık tarihi.", SayfaSayisi = 412, Fiyat = 160.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Sapiens", YeniCikanMi = false, CokSatanMi = true, YazarId = 16, KategoriId = 4, Yayinevi = "Kolektif Kitap", BasimYili = 2011, StokAdedi = 50 },
                new Kitaplar { KitapId = 47, KitapAdi = "Homo Deus: Yarının Kısa Tarihi", Aciklama = "Açlık, savaş ve hastalıkları yenen insanlığın, gelecekte ölümsüzlük, mutluluk ve tanrısallık peşinde koşarken yapay zeka ve biyoteknoloji ile kendi sonunu nasıl hazırlayabileceğini tartışır.", SayfaSayisi = 450, Fiyat = 175.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Homo+Deus", YeniCikanMi = true, CokSatanMi = true, YazarId = 16, KategoriId = 4, Yayinevi = "Kolektif Kitap", BasimYili = 2015, StokAdedi = 50 },
                new Kitaplar { KitapId = 48, KitapAdi = "21. Yüzyıl İçin 21 Ders", Aciklama = "Sahte haberler, teknolojik işsizlik, göçmen krizleri ve ekolojik çöküş gibi günümüzün en yakıcı küresel sorunlarına tarihsel ve felsefi bir mercekten bakan derin bir analiz.", SayfaSayisi = 368, Fiyat = 150.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=21+Ders", YeniCikanMi = false, CokSatanMi = false, YazarId = 16, KategoriId = 4, Yayinevi = "Kolektif Kitap", BasimYili = 2018, StokAdedi = 50 },
                new Kitaplar { KitapId = 49, KitapAdi = "Bir Ömür Nasıl Yaşanır?", Aciklama = "İlber Ortaylı'nın kendi deneyimlerinden yola çıkarak, seyahat etmek, dil öğrenmek, meslek seçimi ve müzik zevki gibi konularda gençlere ufuk açıcı bir yaşam rehberi sunduğu söyleşi kitabı.", SayfaSayisi = 288, Fiyat = 130.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Bir+Omur", YeniCikanMi = false, CokSatanMi = true, YazarId = 10, KategoriId = 4, Yayinevi = "Kronik Kitap", BasimYili = 2019, StokAdedi = 50 },
                new Kitaplar { KitapId = 50, KitapAdi = "Gazi Mustafa Kemal Atatürk", Aciklama = "İlber Ortaylı'nın kaleminden, Mustafa Kemal Atatürk'ün askeri dehasını, vizyonunu, Cumhuriyet'i kurarken verdiği siyasi mücadeleleri tarihi belgeler ışığında anlatan muazzam biyografi.", SayfaSayisi = 480, Fiyat = 195.00m, KapakResimUrl = "https://via.placeholder.com/220x300/1B2A4A/C0C0C0?text=Gazi+Mustafa+Kemal", YeniCikanMi = true, CokSatanMi = true, YazarId = 10, KategoriId = 4, Yayinevi = "Kronik Kitap", BasimYili = 2018, StokAdedi = 50 }
            );
        }
    }
}
