// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaKitap.Models;

#nullable disable

namespace NovaKitap.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506123730_init_2")]
    partial class init_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NovaKitap.Models.Adresler", b =>
                {
                    b.Property<int>("AdresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdresId"));

                    b.Property<string>("AcikAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresBasligi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Sehir")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdresId");

                    b.ToTable("Adresler");
                });

            modelBuilder.Entity("NovaKitap.Models.Kartlar", b =>
                {
                    b.Property<int>("KartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KartId"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KartBasligi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KartNumarasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("SonKullanmaAy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SonKullanmaYil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KartId");

                    b.ToTable("Kartlar");
                });

            modelBuilder.Entity("NovaKitap.Models.Kategoriler", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriId"));

                    b.Property<string>("IkonSifi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KategoriId")
                        .HasName("PK__Kategori__1782CC72FD64979E");

                    b.ToTable("Kategoriler", (string)null);
                });

            modelBuilder.Entity("NovaKitap.Models.Kaydedilenler", b =>
                {
                    b.Property<int>("KayitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KayitId"));

                    b.Property<DateTime?>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("KitapId")
                        .HasColumnType("int");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("KayitId")
                        .HasName("PK__Kaydedil__BD28AF4BD0CD6182");

                    b.HasIndex("KitapId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Kaydedilenler", (string)null);
                });

            modelBuilder.Entity("NovaKitap.Models.Kitaplar", b =>
                {
                    b.Property<int>("KitapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KitapId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BasimYili")
                        .HasColumnType("int");

                    b.Property<bool?>("CokSatanMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("KapakResimUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("KitapAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SayfaSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Yayinevi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YazarId")
                        .HasColumnType("int");

                    b.Property<bool?>("YeniCikanMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("KitapId")
                        .HasName("PK__Kitaplar__89491B0C9F34EF61");

                    b.HasIndex("KategoriId");

                    b.HasIndex("YazarId");

                    b.ToTable("Kitaplar", (string)null);
                });

            modelBuilder.Entity("NovaKitap.Models.Kullanicilar", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KullaniciId")
                        .HasName("PK__Kullanic__E011F77B953AA4E8");

                    b.HasIndex(new[] { "Email" }, "UQ__Kullanic__A9D1053422C2AF0E")
                        .IsUnique();

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("NovaKitap.Models.Siparis", b =>
                {
                    b.Property<int>("SiparisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisId"));

                    b.Property<string>("KargoAdresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("SiparisDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SiparisId");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("NovaKitap.Models.SiparisDetayi", b =>
                {
                    b.Property<int>("SiparisDetayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisDetayId"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KitapId")
                        .HasColumnType("int");

                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.HasKey("SiparisDetayId");

                    b.HasIndex("KitapId");

                    b.HasIndex("SiparisId");

                    b.ToTable("SiparisDetaylari");
                });

            modelBuilder.Entity("NovaKitap.Models.Yazarlar", b =>
                {
                    b.Property<int>("YazarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YazarId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Biyografi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YazarId")
                        .HasName("PK__Yazarlar__CF636CE1C5425819");

                    b.ToTable("Yazarlar", (string)null);
                });

            modelBuilder.Entity("NovaKitap.Models.Kaydedilenler", b =>
                {
                    b.HasOne("NovaKitap.Models.Kitaplar", "Kitap")
                        .WithMany("Kaydedilenlers")
                        .HasForeignKey("KitapId")
                        .HasConstraintName("FK__Kaydedile__Kitap__5812160E");

                    b.HasOne("NovaKitap.Models.Kullanicilar", "Kullanici")
                        .WithMany("Kaydedilenlers")
                        .HasForeignKey("KullaniciId")
                        .HasConstraintName("FK__Kaydedile__Kulla__571DF1D5");

                    b.Navigation("Kitap");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("NovaKitap.Models.Kitaplar", b =>
                {
                    b.HasOne("NovaKitap.Models.Kategoriler", "Kategori")
                        .WithMany("Kitaplars")
                        .HasForeignKey("KategoriId")
                        .HasConstraintName("FK__Kitaplar__Katego__5165187F");

                    b.HasOne("NovaKitap.Models.Yazarlar", "Yazar")
                        .WithMany("Kitaplars")
                        .HasForeignKey("YazarId")
                        .HasConstraintName("FK__Kitaplar__YazarI__5070F446");

                    b.Navigation("Kategori");

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("NovaKitap.Models.SiparisDetayi", b =>
                {
                    b.HasOne("NovaKitap.Models.Kitaplar", "Kitap")
                        .WithMany()
                        .HasForeignKey("KitapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovaKitap.Models.Siparis", "Siparis")
                        .WithMany("SiparişDetaylari")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("NovaKitap.Models.Kategoriler", b =>
                {
                    b.Navigation("Kitaplars");
                });

            modelBuilder.Entity("NovaKitap.Models.Kitaplar", b =>
                {
                    b.Navigation("Kaydedilenlers");
                });

            modelBuilder.Entity("NovaKitap.Models.Kullanicilar", b =>
                {
                    b.Navigation("Kaydedilenlers");
                });

            modelBuilder.Entity("NovaKitap.Models.Siparis", b =>
                {
                    b.Navigation("SiparişDetaylari");
                });

            modelBuilder.Entity("NovaKitap.Models.Yazarlar", b =>
                {
                    b.Navigation("Kitaplars");
                });
#pragma warning restore 612, 618
        }
    }
}
